// src/lib/draft/plantillas-ligas.ts
//
// Plantillas de CLUBES icónicos por liga para el "Draft de Ligas" (pivote del
// antiguo Draft Mundial de selecciones). Mismo formato que las selecciones
// históricas (11 jugadores con posición + fuerza), pero etiquetadas con `liga`
// para sesgar el draft a la(s) liga(s) que sigue el usuario.
//
// Datos curados (XI icónicos reales), evergreen, sin dependencia de api-football.

import { DraftPlantilla } from "./types";
import { PLANTILLAS } from "./plantillas";
import { getCompetition } from "@/data/competitions";

export const CLUB_PLANTILLAS: DraftPlantilla[] = [
  {"id":"real-madrid-1960","seleccion":"Real Madrid","seleccionSlug":"real-madrid","year":1960,"torneo":"Copa de Europa 1960 (Hampden Park, 7-3)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"rma60-1","nombre":"Rogelio Domínguez","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"rma60-2","nombre":"Marquitos","posicion":"LD","fuerza":78,"perfil":"lateral"},{"id":"rma60-3","nombre":"José Santamaría","posicion":"ZAG","fuerza":88,"perfil":"central"},{"id":"rma60-4","nombre":"Pachín","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"rma60-5","nombre":"José María Zárraga","posicion":"LE","fuerza":79,"perfil":"lateral"},{"id":"rma60-6","nombre":"José María Vidal","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"rma60-7","nombre":"Luis del Sol","posicion":"MEI","fuerza":85,"perfil":"mediapunta"},{"id":"rma60-8","nombre":"Ferenc Puskás","posicion":"MEI","fuerza":95,"perfil":"segundo-delantero"},{"id":"rma60-9","nombre":"Canário","posicion":"PD","fuerza":83,"perfil":"extremo"},{"id":"rma60-10","nombre":"Alfredo Di Stéfano","posicion":"CA","fuerza":97,"perfil":"goleador"},{"id":"rma60-11","nombre":"Francisco Gento","posicion":"PI","fuerza":93,"perfil":"extremo"}]},
  {"id":"fc-barcelona-1992","seleccion":"FC Barcelona","seleccionSlug":"fc-barcelona","year":1992,"torneo":"Copa de Europa 1992 (Dream Team de Cruyff)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"fcb92-1","nombre":"Andoni Zubizarreta","posicion":"GOL","fuerza":87,"perfil":"portero"},{"id":"fcb92-2","nombre":"Albert Ferrer","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"fcb92-3","nombre":"Ronald Koeman","posicion":"ZAG","fuerza":89,"perfil":"libero"},{"id":"fcb92-4","nombre":"Nando","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"fcb92-5","nombre":"Juan Carlos","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"fcb92-6","nombre":"Pep Guardiola","posicion":"MCD","fuerza":86,"perfil":"playmaker"},{"id":"fcb92-7","nombre":"Eusebio Sacristán","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"fcb92-8","nombre":"José Mari Bakero","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"fcb92-9","nombre":"Michael Laudrup","posicion":"MEI","fuerza":90,"perfil":"playmaker"},{"id":"fcb92-10","nombre":"Hristo Stoichkov","posicion":"PI","fuerza":91,"perfil":"extremo"},{"id":"fcb92-11","nombre":"Julio Salinas","posicion":"CA","fuerza":80,"perfil":"goleador"}]},
  {"id":"atletico-madrid-1996","seleccion":"Atlético de Madrid","seleccionSlug":"atletico-madrid","year":1996,"torneo":"Doblete Liga y Copa 1995-96 (Antić)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"atm96-1","nombre":"José Francisco Molina","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"atm96-2","nombre":"Delfí Geli","posicion":"LD","fuerza":77,"perfil":"lateral"},{"id":"atm96-3","nombre":"Santi Denia","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"atm96-4","nombre":"Roberto Solozábal","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"atm96-5","nombre":"Toni Muñoz","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"atm96-6","nombre":"Diego Simeone","posicion":"MCD","fuerza":86,"perfil":"volante"},{"id":"atm96-7","nombre":"Juan Vizcaíno","posicion":"VOL","fuerza":77,"perfil":"volante"},{"id":"atm96-8","nombre":"José Luis Caminero","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"atm96-9","nombre":"Milinko Pantić","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"atm96-10","nombre":"Kiko Narváez","posicion":"CA","fuerza":85,"perfil":"segundo-delantero"},{"id":"atm96-11","nombre":"Luboslav Penev","posicion":"CA","fuerza":82,"perfil":"goleador"}]},
  {"id":"valencia-2002","seleccion":"Valencia CF","seleccionSlug":"valencia-cf","year":2002,"torneo":"LaLiga 2001-02 (Rafa Benítez)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"vcf02-1","nombre":"Santiago Cañizares","posicion":"GOL","fuerza":86,"perfil":"portero"},{"id":"vcf02-2","nombre":"Curro Torres","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"vcf02-3","nombre":"Roberto Ayala","posicion":"ZAG","fuerza":86,"perfil":"central"},{"id":"vcf02-4","nombre":"Mauricio Pellegrino","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"vcf02-5","nombre":"Amedeo Carboni","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"vcf02-6","nombre":"David Albelda","posicion":"MCD","fuerza":82,"perfil":"volante"},{"id":"vcf02-7","nombre":"Rubén Baraja","posicion":"VOL","fuerza":84,"perfil":"volante"},{"id":"vcf02-8","nombre":"Pablo Aimar","posicion":"MEI","fuerza":87,"perfil":"playmaker"},{"id":"vcf02-9","nombre":"Vicente Rodríguez","posicion":"PI","fuerza":82,"perfil":"extremo"},{"id":"vcf02-10","nombre":"Miguel Ángel Angulo","posicion":"PD","fuerza":76,"perfil":"extremo"},{"id":"vcf02-11","nombre":"John Carew","posicion":"CA","fuerza":80,"perfil":"goleador"}]},
  {"id":"sevilla-2007","seleccion":"Sevilla FC","seleccionSlug":"sevilla-fc","year":2007,"torneo":"Copa de la UEFA 2007 (Juande Ramos)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"sev07-1","nombre":"Andrés Palop","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"sev07-2","nombre":"Daniel Alves","posicion":"LD","fuerza":86,"perfil":"lateral-ofensivo"},{"id":"sev07-3","nombre":"Julien Escudé","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"sev07-4","nombre":"Javi Navarro","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"sev07-5","nombre":"Ivica Dragutinović","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"sev07-6","nombre":"Christian Poulsen","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"sev07-7","nombre":"Renato","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"sev07-8","nombre":"Jesús Navas","posicion":"EXT","fuerza":85,"perfil":"extremo"},{"id":"sev07-9","nombre":"Antonio Puerta","posicion":"EXT","fuerza":78,"perfil":"extremo"},{"id":"sev07-10","nombre":"Frédéric Kanouté","posicion":"CA","fuerza":87,"perfil":"goleador"},{"id":"sev07-11","nombre":"Luís Fabiano","posicion":"CA","fuerza":84,"perfil":"goleador"}]},
  {"id":"deportivo-2000","seleccion":"Deportivo de La Coruña","seleccionSlug":"deportivo-la-coruna","year":2000,"torneo":"LaLiga 1999-2000 (Súper Dépor, Irureta)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"dep00-1","nombre":"Jacques Songo'o","posicion":"GOL","fuerza":81,"perfil":"portero"},{"id":"dep00-2","nombre":"Manuel Pablo","posicion":"LD","fuerza":77,"perfil":"lateral"},{"id":"dep00-3","nombre":"Nourredine Naybet","posicion":"ZAG","fuerza":83,"perfil":"central"},{"id":"dep00-4","nombre":"César Martín","posicion":"ZAG","fuerza":75,"perfil":"central"},{"id":"dep00-5","nombre":"Enrique Romero","posicion":"LE","fuerza":74,"perfil":"lateral"},{"id":"dep00-6","nombre":"Mauro Silva","posicion":"MCD","fuerza":83,"perfil":"volante"},{"id":"dep00-7","nombre":"Flávio Conceição","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"dep00-8","nombre":"Djalminha","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"dep00-9","nombre":"Víctor Sánchez","posicion":"PD","fuerza":77,"perfil":"extremo"},{"id":"dep00-10","nombre":"Fran","posicion":"PI","fuerza":82,"perfil":"extremo"},{"id":"dep00-11","nombre":"Roy Makaay","posicion":"CA","fuerza":84,"perfil":"goleador"}]},
  {"id":"real-sociedad-1982","seleccion":"Real Sociedad","seleccionSlug":"real-sociedad","year":1982,"torneo":"LaLiga 1981-82 (Ormaetxea)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"rso82-1","nombre":"Luis Arconada","posicion":"GOL","fuerza":88,"perfil":"portero"},{"id":"rso82-2","nombre":"Celayeta","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"rso82-3","nombre":"Alberto Górriz","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"rso82-4","nombre":"Iñaki Kortabarria","posicion":"ZAG","fuerza":78,"perfil":"libero"},{"id":"rso82-5","nombre":"Olaizola","posicion":"LE","fuerza":73,"perfil":"lateral"},{"id":"rso82-6","nombre":"Periko Alonso","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"rso82-7","nombre":"Jesús María Zamora","posicion":"MEI","fuerza":81,"perfil":"mediapunta"},{"id":"rso82-8","nombre":"José Diego","posicion":"VOL","fuerza":74,"perfil":"volante"},{"id":"rso82-9","nombre":"Roberto López Ufarte","posicion":"PI","fuerza":84,"perfil":"extremo"},{"id":"rso82-10","nombre":"Jesús María Satrústegui","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"rso82-11","nombre":"Pedro Uralde","posicion":"PD","fuerza":74,"perfil":"extremo"}]},
  {"id":"athletic-club-2012","seleccion":"Athletic Club","seleccionSlug":"athletic-club","year":2012,"torneo":"Europa League 2012 (Athletic de Bielsa)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"ath12-1","nombre":"Gorka Iraizoz","posicion":"GOL","fuerza":78,"perfil":"portero"},{"id":"ath12-2","nombre":"Andoni Iraola","posicion":"LD","fuerza":79,"perfil":"lateral-ofensivo"},{"id":"ath12-3","nombre":"Fernando Amorebieta","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"ath12-4","nombre":"Javi Martínez","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"ath12-5","nombre":"Jon Aurtenetxe","posicion":"LE","fuerza":70,"perfil":"lateral"},{"id":"ath12-6","nombre":"Ander Iturraspe","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"ath12-7","nombre":"Ander Herrera","posicion":"MEI","fuerza":83,"perfil":"mediapunta"},{"id":"ath12-8","nombre":"Óscar de Marcos","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"ath12-9","nombre":"Markel Susaeta","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"ath12-10","nombre":"Fernando Llorente","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"ath12-11","nombre":"Iker Muniain","posicion":"PI","fuerza":80,"perfil":"extremo"}]},
  {"id":"america-1988","seleccion":"Club América","seleccionSlug":"club-america","year":1988,"torneo":"Liga MX (Primera División) — bicampeonato 1987-88","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"ame88-1","nombre":"Adrián Chávez","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"ame88-2","nombre":"Alfredo Tena","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"ame88-3","nombre":"Carlos Hermosillo","posicion":"CA","fuerza":86,"perfil":"goleador"},{"id":"ame88-4","nombre":"Cristóbal Ortega","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"ame88-5","nombre":"Antonio Carlos Santos","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"ame88-6","nombre":"Daniel Brailovsky","posicion":"MEI","fuerza":84,"perfil":"mediapunta"},{"id":"ame88-7","nombre":"Juan Hernández","posicion":"LD","fuerza":78,"perfil":"lateral"},{"id":"ame88-8","nombre":"Mario Trejo","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"ame88-9","nombre":"Miguel Ángel Herrera","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"ame88-10","nombre":"Roberto Ruiz Esparza","posicion":"VOL","fuerza":77,"perfil":"volante"},{"id":"ame88-11","nombre":"Luis Roberto Alves Zague","posicion":"PD","fuerza":84,"perfil":"extremo"}]},
  {"id":"chivas-2017","seleccion":"Chivas de Guadalajara","seleccionSlug":"chivas","year":2017,"torneo":"Liga MX — campeón Clausura 2017","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"chi17-1","nombre":"Rodolfo Cota","posicion":"GOL","fuerza":80,"perfil":"portero"},{"id":"chi17-2","nombre":"Jair Pereira","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"chi17-3","nombre":"Óscar Bautista","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"chi17-4","nombre":"Carlos Salcido","posicion":"LE","fuerza":82,"perfil":"lateral-ofensivo"},{"id":"chi17-5","nombre":"Edwin Hernández","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"chi17-6","nombre":"Michael Pérez","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"chi17-7","nombre":"Orbelín Pineda","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"chi17-8","nombre":"Rodolfo Pizarro","posicion":"MEI","fuerza":83,"perfil":"playmaker"},{"id":"chi17-9","nombre":"Isaác Brizuela","posicion":"EXT","fuerza":78,"perfil":"extremo"},{"id":"chi17-10","nombre":"Alan Pulido","posicion":"CA","fuerza":83,"perfil":"goleador"},{"id":"chi17-11","nombre":"Ángel Zaldívar","posicion":"CA","fuerza":75,"perfil":"goleador"}]},
  {"id":"cruzazul-1997","seleccion":"Cruz Azul","seleccionSlug":"cruz-azul","year":1997,"torneo":"Liga MX — campeón Invierno 1997","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"cru97-1","nombre":"Óscar Pérez","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"cru97-2","nombre":"Joel Sánchez","posicion":"LD","fuerza":79,"perfil":"lateral"},{"id":"cru97-3","nombre":"Ricardo Peláez","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"cru97-4","nombre":"Carlos Hermosillo","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"cru97-5","nombre":"Francisco Palencia","posicion":"PI","fuerza":82,"perfil":"extremo"},{"id":"cru97-6","nombre":"Israel López","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"cru97-7","nombre":"Juan Reynoso","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"cru97-8","nombre":"Carlos Muñoz","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"cru97-9","nombre":"José Saturnino Cardozo","posicion":"MEI","fuerza":79,"perfil":"mediapunta"},{"id":"cru97-10","nombre":"Marcelo Balboa","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"cru97-11","nombre":"José de Jesús Ramírez","posicion":"VOL","fuerza":75,"perfil":"volante"}]},
  {"id":"pumas-2004","seleccion":"Pumas UNAM","seleccionSlug":"pumas-unam","year":2004,"torneo":"Liga MX — bicampeón Clausura/Apertura 2004","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"pum04-1","nombre":"Sergio Bernal","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"pum04-2","nombre":"Darío Verón","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"pum04-3","nombre":"Gabriel Caballero","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"pum04-4","nombre":"Israel Castro","posicion":"VOL","fuerza":77,"perfil":"volante"},{"id":"pum04-5","nombre":"Joaquín Beltrán","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"pum04-6","nombre":"Leandro Augusto","posicion":"MEI","fuerza":80,"perfil":"playmaker"},{"id":"pum04-7","nombre":"Ailton da Silva","posicion":"CA","fuerza":79,"perfil":"goleador"},{"id":"pum04-8","nombre":"Jaime Lozano","posicion":"MEI","fuerza":78,"perfil":"mediapunta"},{"id":"pum04-9","nombre":"Bruno Marioni","posicion":"CA","fuerza":80,"perfil":"goleador"},{"id":"pum04-10","nombre":"Diego Alonso","posicion":"PD","fuerza":77,"perfil":"extremo"},{"id":"pum04-11","nombre":"Marco Antonio Palacios","posicion":"LD","fuerza":74,"perfil":"lateral"}]},
  {"id":"tigres-2018","seleccion":"Tigres UANL","seleccionSlug":"tigres-uanl","year":2018,"torneo":"Liga MX — era Gignac, tetracampeón (Apertura 2017)","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"tig18-1","nombre":"Nahuel Guzmán","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"tig18-2","nombre":"Juninho","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"tig18-3","nombre":"Hugo Ayala","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"tig18-4","nombre":"Jorge Torres Nilo","posicion":"LE","fuerza":79,"perfil":"lateral"},{"id":"tig18-5","nombre":"Luis Rodríguez","posicion":"LD","fuerza":80,"perfil":"lateral-ofensivo"},{"id":"tig18-6","nombre":"Guido Pizarro","posicion":"MCD","fuerza":83,"perfil":"volante"},{"id":"tig18-7","nombre":"Rafael Sóbis","posicion":"MEI","fuerza":81,"perfil":"segundo-delantero"},{"id":"tig18-8","nombre":"Javier Aquino","posicion":"EXT","fuerza":80,"perfil":"extremo"},{"id":"tig18-9","nombre":"Jürgen Damm","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"tig18-10","nombre":"André-Pierre Gignac","posicion":"CA","fuerza":88,"perfil":"goleador"},{"id":"tig18-11","nombre":"Eduardo Vargas","posicion":"PI","fuerza":81,"perfil":"extremo"}]},
  {"id":"monterrey-2019","seleccion":"Monterrey","seleccionSlug":"monterrey","year":2019,"torneo":"Liga MX — campeón Apertura 2019","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"mty19-1","nombre":"Marcelo Barovero","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"mty19-2","nombre":"Nicolás Sánchez","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"mty19-3","nombre":"César Montes","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"mty19-4","nombre":"Leonel Vangioni","posicion":"LE","fuerza":79,"perfil":"lateral-ofensivo"},{"id":"mty19-5","nombre":"Miguel Layún","posicion":"LD","fuerza":82,"perfil":"lateral-ofensivo"},{"id":"mty19-6","nombre":"Celso Ortiz","posicion":"MCD","fuerza":79,"perfil":"volante"},{"id":"mty19-7","nombre":"Carlos Rodríguez","posicion":"VOL","fuerza":80,"perfil":"volante"},{"id":"mty19-8","nombre":"Rogelio Funes Mori","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"mty19-9","nombre":"Dorlan Pabón","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"mty19-10","nombre":"Rodolfo Pizarro","posicion":"EXT","fuerza":82,"perfil":"extremo"},{"id":"mty19-11","nombre":"Maximiliano Meza","posicion":"PD","fuerza":80,"perfil":"extremo"}]},
  {"id":"toluca-2008","seleccion":"Toluca","seleccionSlug":"toluca","year":2008,"torneo":"Liga MX — campeón Apertura 2008","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"tol08-1","nombre":"Hernán Cristante","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"tol08-2","nombre":"Manuel de la Torre","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"tol08-3","nombre":"Paulo da Silva","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"tol08-4","nombre":"Diego Novaretti","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"tol08-5","nombre":"Marco Antonio Rodríguez","posicion":"LE","fuerza":74,"perfil":"lateral"},{"id":"tol08-6","nombre":"Antonio Naelson Sinha","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"tol08-7","nombre":"Israel López","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"tol08-8","nombre":"José Cardozo","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"tol08-9","nombre":"Vicente Sánchez","posicion":"MEI","fuerza":81,"perfil":"segundo-delantero"},{"id":"tol08-10","nombre":"Héctor Mancilla","posicion":"CA","fuerza":80,"perfil":"goleador"},{"id":"tol08-11","nombre":"Edgar Dueñas","posicion":"VOL","fuerza":75,"perfil":"volante"}]},
  {"id":"ldu-quito-2008","seleccion":"LDU de Quito","seleccionSlug":"ldu-quito","year":2008,"torneo":"Campeón Copa Libertadores 2008","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"ldu08-1","nombre":"José Francisco Cevallos","posicion":"GOL","fuerza":90,"perfil":"portero"},{"id":"ldu08-2","nombre":"Norberto Araujo","posicion":"ZAG","fuerza":86,"perfil":"central"},{"id":"ldu08-3","nombre":"Jorge Guagua","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"ldu08-4","nombre":"Diego Calderón","posicion":"LD","fuerza":79,"perfil":"lateral"},{"id":"ldu08-5","nombre":"Enrique Vera","posicion":"MCD","fuerza":85,"perfil":"volante"},{"id":"ldu08-6","nombre":"Patricio Urrutia","posicion":"MEI","fuerza":86,"perfil":"playmaker"},{"id":"ldu08-7","nombre":"William Araujo","posicion":"VOL","fuerza":78,"perfil":"volante"},{"id":"ldu08-8","nombre":"Damián Manso","posicion":"MEI","fuerza":83,"perfil":"mediapunta"},{"id":"ldu08-9","nombre":"Claudio Bieler","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"ldu08-10","nombre":"Luis Bolaños","posicion":"EXT","fuerza":83,"perfil":"extremo"},{"id":"ldu08-11","nombre":"Joffre Guerrón","posicion":"PI","fuerza":82,"perfil":"extremo"}]},
  {"id":"barcelona-sc-1990","seleccion":"Barcelona SC","seleccionSlug":"barcelona-sc","year":1990,"torneo":"Finalista Copa Libertadores 1990","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"bsc90-1","nombre":"Carlos Luis Morales","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"bsc90-2","nombre":"Luis Capurro","posicion":"LD","fuerza":82,"perfil":"lateral"},{"id":"bsc90-3","nombre":"Raúl Noriega","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"bsc90-4","nombre":"Luis Fernando Mora","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"bsc90-5","nombre":"Wellington Sánchez","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"bsc90-6","nombre":"Marcelo Trobbiani","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"bsc90-7","nombre":"Severino Vasconcelos","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"bsc90-8","nombre":"Rubén Insúa","posicion":"MEI","fuerza":81,"perfil":"mediapunta"},{"id":"bsc90-9","nombre":"José Gavica","posicion":"CA","fuerza":80,"perfil":"goleador"},{"id":"bsc90-10","nombre":"Nicolás Asencio","posicion":"PD","fuerza":78,"perfil":"extremo"},{"id":"bsc90-11","nombre":"Gonzalo Chila","posicion":"PI","fuerza":76,"perfil":"extremo"}]},
  {"id":"barcelona-sc-2017","seleccion":"Barcelona SC","seleccionSlug":"barcelona-sc","year":2017,"torneo":"Campeón Serie A 2016 / Semifinal Libertadores 2017","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"bsc17-1","nombre":"Máximo Banguera","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"bsc17-2","nombre":"Mario Pineida","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"bsc17-3","nombre":"Darío Aimar","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"bsc17-4","nombre":"Dario Aimar Guagua","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"bsc17-5","nombre":"Gabriel Marques","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"bsc17-6","nombre":"Matías Oyola","posicion":"MCD","fuerza":81,"perfil":"volante"},{"id":"bsc17-7","nombre":"Jonatan Álvez","posicion":"CA","fuerza":80,"perfil":"goleador"},{"id":"bsc17-8","nombre":"Damián Díaz","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"bsc17-9","nombre":"Michael Arroyo","posicion":"EXT","fuerza":82,"perfil":"extremo"},{"id":"bsc17-10","nombre":"Jonathan Betancourt","posicion":"VOL","fuerza":74,"perfil":"volante"},{"id":"bsc17-11","nombre":"Marcos Caicedo","posicion":"PI","fuerza":77,"perfil":"extremo"}]},
  {"id":"emelec-2013","seleccion":"Emelec","seleccionSlug":"emelec","year":2013,"torneo":"Campeón Serie A 2013 (tricampeón 2013-15)","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"eme13-1","nombre":"Esteban Dreer","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"eme13-2","nombre":"Óscar Bagüí","posicion":"LE","fuerza":80,"perfil":"lateral-ofensivo"},{"id":"eme13-3","nombre":"Gabriel Achilier","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"eme13-4","nombre":"Jaime Ayoví Corozo","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"eme13-5","nombre":"Fernando Giménez","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"eme13-6","nombre":"Pedro Quiñónez","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"eme13-7","nombre":"Marcos Mondaini","posicion":"MEI","fuerza":82,"perfil":"playmaker"},{"id":"eme13-8","nombre":"Fernando Gaibor","posicion":"VOL","fuerza":78,"perfil":"volante"},{"id":"eme13-9","nombre":"Miller Bolaños","posicion":"MEI","fuerza":83,"perfil":"mediapunta"},{"id":"eme13-10","nombre":"Marlon de Jesús","posicion":"CA","fuerza":79,"perfil":"goleador"},{"id":"eme13-11","nombre":"Enner Valencia","posicion":"PD","fuerza":84,"perfil":"goleador"}]},
  {"id":"independiente-del-valle-2016","seleccion":"Independiente del Valle","seleccionSlug":"independiente-del-valle","year":2016,"torneo":"Finalista Copa Libertadores 2016","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"idv16-1","nombre":"Jorge Pinos","posicion":"GOL","fuerza":78,"perfil":"portero"},{"id":"idv16-2","nombre":"Luis Segovia","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"idv16-3","nombre":"Arturo Mina","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"idv16-4","nombre":"Cristian Pellerano","posicion":"MCD","fuerza":81,"perfil":"volante"},{"id":"idv16-5","nombre":"Jefferson Orejuela","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"idv16-6","nombre":"Fernando Guerrero","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"idv16-7","nombre":"Junior Sornoza","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"idv16-8","nombre":"Gabriel Cortez","posicion":"LE","fuerza":75,"perfil":"lateral-ofensivo"},{"id":"idv16-9","nombre":"Bryan Cabezas","posicion":"EXT","fuerza":79,"perfil":"extremo"},{"id":"idv16-10","nombre":"Jonatan Borja","posicion":"PI","fuerza":77,"perfil":"extremo"},{"id":"idv16-11","nombre":"Jaime Ayoví","posicion":"CA","fuerza":80,"perfil":"goleador"}]},
  {"id":"deportivo-quito-2009","seleccion":"Deportivo Quito","seleccionSlug":"deportivo-quito","year":2009,"torneo":"Bicampeón Serie A 2008-2009","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"dq09-1","nombre":"Marcelo Elizaga","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"dq09-2","nombre":"Néicer Reasco","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"dq09-3","nombre":"Luis Checa","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"dq09-4","nombre":"Renán Calle","posicion":"ZAG","fuerza":75,"perfil":"central"},{"id":"dq09-5","nombre":"Frickson Erazo","posicion":"LE","fuerza":78,"perfil":"central"},{"id":"dq09-6","nombre":"Juan Carlos Paredes","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"dq09-7","nombre":"Marlon Ayoví","posicion":"VOL","fuerza":77,"perfil":"volante"},{"id":"dq09-8","nombre":"Luis Saritama","posicion":"MEI","fuerza":81,"perfil":"playmaker"},{"id":"dq09-9","nombre":"Maximiliano Bevacqua","posicion":"CA","fuerza":79,"perfil":"goleador"},{"id":"dq09-10","nombre":"Luis Fernando Saritama","posicion":"PD","fuerza":74,"perfil":"extremo"},{"id":"dq09-11","nombre":"Patricio Toranzo","posicion":"PI","fuerza":78,"perfil":"extremo"}]},
  {"id":"el-nacional-2005","seleccion":"El Nacional","seleccionSlug":"el-nacional","year":2005,"torneo":"Campeón Serie A 2005 (Apertura y Clausura)","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"nac05-1","nombre":"Cristian Mora","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"nac05-2","nombre":"Ulises de la Cruz","posicion":"LD","fuerza":83,"perfil":"lateral-ofensivo"},{"id":"nac05-3","nombre":"Edwin Tenorio","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"nac05-4","nombre":"Jairo Campos","posicion":"ZAG","fuerza":74,"perfil":"central"},{"id":"nac05-5","nombre":"Carlos Espínola","posicion":"LE","fuerza":73,"perfil":"lateral"},{"id":"nac05-6","nombre":"Alfonso Obregón","posicion":"MCD","fuerza":79,"perfil":"volante"},{"id":"nac05-7","nombre":"Segundo Castillo","posicion":"VOL","fuerza":82,"perfil":"volante"},{"id":"nac05-8","nombre":"Luis Antonio Valencia","posicion":"PD","fuerza":85,"perfil":"extremo"},{"id":"nac05-9","nombre":"Édison Méndez","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"nac05-10","nombre":"Agustín Delgado","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"nac05-11","nombre":"Franklin Salas","posicion":"PI","fuerza":78,"perfil":"extremo"}]},
  {"id":"independiente-1974","seleccion":"Independiente","seleccionSlug":"independiente","year":1974,"torneo":"El Rey de Copas · Tetracampeón de América 1972-1975","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"ind74-1","nombre":"Miguel Ángel Santoro","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"ind74-2","nombre":"Roberto Semenewicz","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"ind74-3","nombre":"Francisco Sá","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"ind74-4","nombre":"Enzo Trossero","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"ind74-5","nombre":"Ricardo Pavoni","posicion":"LE","fuerza":80,"perfil":"lateral"},{"id":"ind74-6","nombre":"José Omar Pastoriza","posicion":"MCD","fuerza":82,"perfil":"volante"},{"id":"ind74-7","nombre":"Rubén Galván","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"ind74-8","nombre":"Ricardo Bochini","posicion":"MEI","fuerza":90,"perfil":"playmaker"},{"id":"ind74-9","nombre":"Agustín Balbuena","posicion":"PD","fuerza":80,"perfil":"extremo"},{"id":"ind74-10","nombre":"Daniel Bertoni","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"ind74-11","nombre":"Percy Rojas","posicion":"PI","fuerza":79,"perfil":"extremo"}]},
  {"id":"racing-1967","seleccion":"Racing Club","seleccionSlug":"racing-club","year":1967,"torneo":"El Equipo de José · Campeón Intercontinental 1967","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"rac67-1","nombre":"Agustín Cejas","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"rac67-2","nombre":"Oscar Martín","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"rac67-3","nombre":"Roberto Perfumo","posicion":"ZAG","fuerza":88,"perfil":"central"},{"id":"rac67-4","nombre":"Alfio Basile","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"rac67-5","nombre":"Nelson Chabay","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"rac67-6","nombre":"Juan Carlos Rulli","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"rac67-7","nombre":"Juan José Rodríguez","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"rac67-8","nombre":"Humberto Maschio","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"rac67-9","nombre":"Norberto Raffo","posicion":"PD","fuerza":83,"perfil":"goleador"},{"id":"rac67-10","nombre":"Juan Carlos Cárdenas","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"rac67-11","nombre":"Alfredo Obberti","posicion":"PI","fuerza":74,"perfil":"extremo"}]},
  {"id":"estudiantes-1969","seleccion":"Estudiantes de La Plata","seleccionSlug":"estudiantes-la-plata","year":1969,"torneo":"Tricampeón de América 1968-1970 · era Zubeldía","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"est69-1","nombre":"Alberto Poletti","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"est69-2","nombre":"Eduardo Manera","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"est69-3","nombre":"Ramón Aguirre Suárez","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"est69-4","nombre":"Néstor Togneri","posicion":"ZAG","fuerza":78,"perfil":"libero"},{"id":"est69-5","nombre":"Oscar Malbernat","posicion":"LE","fuerza":79,"perfil":"lateral"},{"id":"est69-6","nombre":"Carlos Bilardo","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"est69-7","nombre":"Carlos Pachamé","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"est69-8","nombre":"Felipe Ribaudo","posicion":"MEI","fuerza":77,"perfil":"mediapunta"},{"id":"est69-9","nombre":"Juan Ramón Verón","posicion":"PD","fuerza":86,"perfil":"extremo"},{"id":"est69-10","nombre":"Marcos Conigliaro","posicion":"CA","fuerza":81,"perfil":"goleador"},{"id":"est69-11","nombre":"Juan Echecopar","posicion":"PI","fuerza":75,"perfil":"extremo"}]},
  {"id":"newells-1991","seleccion":"Newell's Old Boys","seleccionSlug":"newells-old-boys","year":1991,"torneo":"La Lepra de Bielsa · finalista Libertadores 1992","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"nob91-1","nombre":"Norberto Scoponi","posicion":"GOL","fuerza":81,"perfil":"portero"},{"id":"nob91-2","nombre":"Fabián Garfagnoli","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"nob91-3","nombre":"Fernando Gamboa","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"nob91-4","nombre":"Mauricio Pochettino","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"nob91-5","nombre":"Eduardo Berizzo","posicion":"LE","fuerza":79,"perfil":"lateral"},{"id":"nob91-6","nombre":"Juan Manuel Llop","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"nob91-7","nombre":"Gerardo Martino","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"nob91-8","nombre":"Darío Franco","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"nob91-9","nombre":"Alfredo Mendoza","posicion":"PI","fuerza":77,"perfil":"extremo"},{"id":"nob91-10","nombre":"Cristian Domizzi","posicion":"CA","fuerza":79,"perfil":"goleador"},{"id":"nob91-11","nombre":"Gustavo Raggio","posicion":"PD","fuerza":75,"perfil":"extremo"}]},
  {"id":"velez-1994","seleccion":"Vélez Sarsfield","seleccionSlug":"velez-sarsfield","year":1994,"torneo":"Campeón Intercontinental 1994 · Bianchi","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"vel94-1","nombre":"José Luis Chilavert","posicion":"GOL","fuerza":90,"perfil":"portero"},{"id":"vel94-2","nombre":"Raúl Cardozo","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"vel94-3","nombre":"Roberto Trotta","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"vel94-4","nombre":"Víctor Sotomayor","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"vel94-5","nombre":"Alberto Bica","posicion":"LE","fuerza":75,"perfil":"lateral"},{"id":"vel94-6","nombre":"José Basualdo","posicion":"VOL","fuerza":82,"perfil":"volante"},{"id":"vel94-7","nombre":"Christian Bassedas","posicion":"MCD","fuerza":81,"perfil":"volante"},{"id":"vel94-8","nombre":"Marcelo Gómez","posicion":"MEI","fuerza":78,"perfil":"mediapunta"},{"id":"vel94-9","nombre":"Roberto Pompei","posicion":"PD","fuerza":78,"perfil":"extremo"},{"id":"vel94-10","nombre":"Omar Asad","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"vel94-11","nombre":"José Oscar Flores","posicion":"PI","fuerza":77,"perfil":"extremo"}]},
  {"id":"river-1996","seleccion":"River Plate","seleccionSlug":"river-plate","year":1996,"torneo":"Campeón Copa Libertadores 1996 · Los Millonarios de Ramón Díaz","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"riv96-1","nombre":"Germán Burgos","posicion":"GOL","fuerza":83,"perfil":"portero"},{"id":"riv96-2","nombre":"Hernán Díaz","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"riv96-3","nombre":"Celso Ayala","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"riv96-4","nombre":"Roberto Ayala","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"riv96-5","nombre":"Juan Pablo Sorín","posicion":"LE","fuerza":82,"perfil":"lateral-ofensivo"},{"id":"riv96-6","nombre":"Leonardo Astrada","posicion":"MCD","fuerza":81,"perfil":"volante"},{"id":"riv96-7","nombre":"Matías Almeyda","posicion":"VOL","fuerza":82,"perfil":"volante"},{"id":"riv96-8","nombre":"Enzo Francescoli","posicion":"MEI","fuerza":90,"perfil":"playmaker"},{"id":"riv96-9","nombre":"Ariel Ortega","posicion":"EXT","fuerza":86,"perfil":"mediapunta"},{"id":"riv96-10","nombre":"Hernán Crespo","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"riv96-11","nombre":"Marcelo Gallardo","posicion":"CA","fuerza":84,"perfil":"segundo-delantero"}]},
  {"id":"boca-2000","seleccion":"Boca Juniors","seleccionSlug":"boca-juniors","year":2000,"torneo":"Campeón Intercontinental 2000 · era Bianchi","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"boca00-1","nombre":"Óscar Córdoba","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"boca00-2","nombre":"Hugo Ibarra","posicion":"LD","fuerza":78,"perfil":"lateral"},{"id":"boca00-3","nombre":"Jorge Bermúdez","posicion":"ZAG","fuerza":83,"perfil":"central"},{"id":"boca00-4","nombre":"Walter Samuel","posicion":"ZAG","fuerza":86,"perfil":"central"},{"id":"boca00-5","nombre":"Rodolfo Arruabarrena","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"boca00-6","nombre":"Mauricio Serna","posicion":"MCD","fuerza":79,"perfil":"volante"},{"id":"boca00-7","nombre":"Sebastián Battaglia","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"boca00-8","nombre":"Juan Román Riquelme","posicion":"MEI","fuerza":92,"perfil":"playmaker"},{"id":"boca00-9","nombre":"Guillermo Barros Schelotto","posicion":"EXT","fuerza":85,"perfil":"extremo"},{"id":"boca00-10","nombre":"Martín Palermo","posicion":"CA","fuerza":88,"perfil":"goleador"},{"id":"boca00-11","nombre":"Marcelo Delgado","posicion":"CA","fuerza":81,"perfil":"segundo-delantero"}]},
  {"id":"san-lorenzo-2014","seleccion":"San Lorenzo","seleccionSlug":"san-lorenzo","year":2014,"torneo":"Campeón Copa Libertadores 2014 · Bauza","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"sl14-1","nombre":"Sebastián Torrico","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"sl14-2","nombre":"Julio Buffarini","posicion":"LD","fuerza":77,"perfil":"lateral"},{"id":"sl14-3","nombre":"Walter Kannemann","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"sl14-4","nombre":"Santiago Gentiletti","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"sl14-5","nombre":"Emmanuel Mas","posicion":"LE","fuerza":78,"perfil":"lateral"},{"id":"sl14-6","nombre":"Juan Mercier","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"sl14-7","nombre":"Néstor Ortigoza","posicion":"VOL","fuerza":82,"perfil":"playmaker"},{"id":"sl14-8","nombre":"Leandro Romagnoli","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"sl14-9","nombre":"Ignacio Piatti","posicion":"PI","fuerza":83,"perfil":"extremo"},{"id":"sl14-10","nombre":"Mauro Matos","posicion":"CA","fuerza":78,"perfil":"goleador"},{"id":"sl14-11","nombre":"Ángel Correa","posicion":"PD","fuerza":78,"perfil":"extremo"}]},
  {"id":"santos-1962","seleccion":"Santos","seleccionSlug":"santos","year":1962,"torneo":"Santos de Pelé — Libertadores/Intercontinental 1962","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"san62-1","nombre":"Gilmar","posicion":"GOL","fuerza":88,"perfil":"portero"},{"id":"san62-2","nombre":"Lima","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"san62-3","nombre":"Mauro Ramos","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"san62-4","nombre":"Calvet","posicion":"ZAG","fuerza":75,"perfil":"central"},{"id":"san62-5","nombre":"Dalmo","posicion":"LE","fuerza":75,"perfil":"lateral"},{"id":"san62-6","nombre":"Zito","posicion":"MCD","fuerza":85,"perfil":"volante"},{"id":"san62-7","nombre":"Mengálvio","posicion":"VOL","fuerza":82,"perfil":"playmaker"},{"id":"san62-8","nombre":"Dorval","posicion":"PD","fuerza":81,"perfil":"extremo"},{"id":"san62-9","nombre":"Coutinho","posicion":"CA","fuerza":86,"perfil":"goleador"},{"id":"san62-10","nombre":"Pelé","posicion":"MEI","fuerza":98,"perfil":"mediapunta"},{"id":"san62-11","nombre":"Pepe","posicion":"PI","fuerza":87,"perfil":"extremo"}]},
  {"id":"flamengo-1981","seleccion":"Flamengo","seleccionSlug":"flamengo","year":1981,"torneo":"Flamengo de Zico — Mundial de Clubes 1981","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"fla81-1","nombre":"Raul","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"fla81-2","nombre":"Leandro","posicion":"LD","fuerza":86,"perfil":"lateral-ofensivo"},{"id":"fla81-3","nombre":"Marinho","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"fla81-4","nombre":"Figueiredo","posicion":"ZAG","fuerza":74,"perfil":"central"},{"id":"fla81-5","nombre":"Júnior","posicion":"LE","fuerza":88,"perfil":"lateral-ofensivo"},{"id":"fla81-6","nombre":"Andrade","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"fla81-7","nombre":"Adílio","posicion":"VOL","fuerza":80,"perfil":"volante"},{"id":"fla81-8","nombre":"Zico","posicion":"MEI","fuerza":96,"perfil":"playmaker"},{"id":"fla81-9","nombre":"Tita","posicion":"PD","fuerza":80,"perfil":"extremo"},{"id":"fla81-10","nombre":"Nunes","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"fla81-11","nombre":"Lico","posicion":"PI","fuerza":76,"perfil":"extremo"}]},
  {"id":"sao-paulo-1992","seleccion":"São Paulo","seleccionSlug":"sao-paulo","year":1992,"torneo":"São Paulo de Telê e Raí — Bicampeão Mundial 1992-93","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"spfc92-1","nombre":"Zetti","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"spfc92-2","nombre":"Cafú","posicion":"LD","fuerza":88,"perfil":"lateral-ofensivo"},{"id":"spfc92-3","nombre":"Ronaldão","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"spfc92-4","nombre":"Antônio Carlos","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"spfc92-5","nombre":"Ivan","posicion":"LE","fuerza":73,"perfil":"lateral"},{"id":"spfc92-6","nombre":"Toninho Cerezo","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"spfc92-7","nombre":"Pintado","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"spfc92-8","nombre":"Raí","posicion":"MEI","fuerza":90,"perfil":"playmaker"},{"id":"spfc92-9","nombre":"Válber","posicion":"MEI","fuerza":78,"perfil":"mediapunta"},{"id":"spfc92-10","nombre":"Müller","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"spfc92-11","nombre":"Palhinha","posicion":"PI","fuerza":79,"perfil":"segundo-delantero"}]},
  {"id":"corinthians-2012","seleccion":"Corinthians","seleccionSlug":"corinthians","year":2012,"torneo":"Corinthians Mundial — Libertadores e Mundial 2012","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"cor12-1","nombre":"Cássio","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"cor12-2","nombre":"Alessandro","posicion":"LD","fuerza":78,"perfil":"lateral"},{"id":"cor12-3","nombre":"Chicão","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"cor12-4","nombre":"Leandro Castán","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"cor12-5","nombre":"Fábio Santos","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"cor12-6","nombre":"Ralf","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"cor12-7","nombre":"Paulinho","posicion":"VOL","fuerza":84,"perfil":"volante"},{"id":"cor12-8","nombre":"Danilo","posicion":"MEI","fuerza":79,"perfil":"playmaker"},{"id":"cor12-9","nombre":"Jorge Henrique","posicion":"EXT","fuerza":74,"perfil":"extremo"},{"id":"cor12-10","nombre":"Guerrero","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"cor12-11","nombre":"Emerson Sheik","posicion":"PI","fuerza":80,"perfil":"segundo-delantero"}]},
  {"id":"gremio-1983","seleccion":"Grêmio","seleccionSlug":"gremio","year":1983,"torneo":"Grêmio Campeão do Mundo 1983","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"gre83-1","nombre":"Mazarópi","posicion":"GOL","fuerza":78,"perfil":"portero"},{"id":"gre83-2","nombre":"Paulo Roberto","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"gre83-3","nombre":"Hugo De León","posicion":"ZAG","fuerza":84,"perfil":"libero"},{"id":"gre83-4","nombre":"Osvaldo","posicion":"ZAG","fuerza":73,"perfil":"central"},{"id":"gre83-5","nombre":"China","posicion":"LE","fuerza":72,"perfil":"lateral"},{"id":"gre83-6","nombre":"Casemiro Mior","posicion":"MCD","fuerza":74,"perfil":"volante"},{"id":"gre83-7","nombre":"Bonamigo","posicion":"VOL","fuerza":75,"perfil":"volante"},{"id":"gre83-8","nombre":"Caio","posicion":"MEI","fuerza":76,"perfil":"mediapunta"},{"id":"gre83-9","nombre":"Tarciso","posicion":"PD","fuerza":78,"perfil":"extremo"},{"id":"gre83-10","nombre":"Baltazar","posicion":"CA","fuerza":80,"perfil":"goleador"},{"id":"gre83-11","nombre":"Renato Gaúcho","posicion":"PI","fuerza":85,"perfil":"segundo-delantero"}]},
  {"id":"palmeiras-2020","seleccion":"Palmeiras","seleccionSlug":"palmeiras","year":2020,"torneo":"Palmeiras de Abel — Bi da Libertadores 2020-21","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"pal20-1","nombre":"Weverton","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"pal20-2","nombre":"Marcos Rocha","posicion":"LD","fuerza":77,"perfil":"lateral"},{"id":"pal20-3","nombre":"Gustavo Gómez","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"pal20-4","nombre":"Luan","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"pal20-5","nombre":"Matías Viña","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"pal20-6","nombre":"Zé Rafael","posicion":"MCD","fuerza":79,"perfil":"volante"},{"id":"pal20-7","nombre":"Felipe Melo","posicion":"VOL","fuerza":78,"perfil":"volante"},{"id":"pal20-8","nombre":"Raphael Veiga","posicion":"MEI","fuerza":83,"perfil":"mediapunta"},{"id":"pal20-9","nombre":"Gustavo Scarpa","posicion":"EXT","fuerza":79,"perfil":"extremo"},{"id":"pal20-10","nombre":"Rony","posicion":"PD","fuerza":82,"perfil":"extremo"},{"id":"pal20-11","nombre":"Luiz Adriano","posicion":"CA","fuerza":78,"perfil":"goleador"}]},
  {"id":"cruzeiro-2003","seleccion":"Cruzeiro","seleccionSlug":"cruzeiro","year":2003,"torneo":"Cruzeiro da Tríplice Coroa 2003","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"cru03-1","nombre":"Gomes","posicion":"GOL","fuerza":80,"perfil":"portero"},{"id":"cru03-2","nombre":"Maurinho","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"cru03-3","nombre":"Cris","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"cru03-4","nombre":"Luisão","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"cru03-5","nombre":"Juan Pablo Sorín","posicion":"LE","fuerza":83,"perfil":"lateral-ofensivo"},{"id":"cru03-6","nombre":"Augusto Recife","posicion":"MCD","fuerza":74,"perfil":"volante"},{"id":"cru03-7","nombre":"Ricardinho","posicion":"VOL","fuerza":80,"perfil":"playmaker"},{"id":"cru03-8","nombre":"Alex","posicion":"MEI","fuerza":89,"perfil":"playmaker"},{"id":"cru03-9","nombre":"Mota","posicion":"EXT","fuerza":76,"perfil":"extremo"},{"id":"cru03-10","nombre":"Deivid","posicion":"CA","fuerza":79,"perfil":"goleador"},{"id":"cru03-11","nombre":"Víctor Aristizábal","posicion":"PI","fuerza":81,"perfil":"segundo-delantero"}]},
  {"id":"internacional-2010","seleccion":"Internacional","seleccionSlug":"internacional","year":2010,"torneo":"Internacional de D'Alessandro — Libertadores 2010","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"int10-1","nombre":"Lauro","posicion":"GOL","fuerza":74,"perfil":"portero"},{"id":"int10-2","nombre":"Nei","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"int10-3","nombre":"Bolívar","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"int10-4","nombre":"Índio","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"int10-5","nombre":"Kléber","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"int10-6","nombre":"Sandro","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"int10-7","nombre":"Pablo Guiñazú","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"int10-8","nombre":"Andrés D'Alessandro","posicion":"MEI","fuerza":88,"perfil":"playmaker"},{"id":"int10-9","nombre":"Giuliano","posicion":"EXT","fuerza":81,"perfil":"extremo"},{"id":"int10-10","nombre":"Alecsandro","posicion":"CA","fuerza":77,"perfil":"goleador"},{"id":"int10-11","nombre":"Rafael Sóbis","posicion":"PI","fuerza":80,"perfil":"segundo-delantero"}]},
  {"id":"tottenham-1961","seleccion":"Tottenham Hotspur","seleccionSlug":"tottenham-hotspur","year":1961,"torneo":"The Double: Liga + FA Cup 1960-61","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"tot61-1","nombre":"Bill Brown","posicion":"GOL","fuerza":80,"perfil":"portero"},{"id":"tot61-2","nombre":"Peter Baker","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"tot61-3","nombre":"Ron Henry","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"tot61-4","nombre":"Maurice Norman","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"tot61-5","nombre":"Danny Blanchflower","posicion":"MCD","fuerza":90,"perfil":"playmaker"},{"id":"tot61-6","nombre":"Dave Mackay","posicion":"VOL","fuerza":91,"perfil":"volante"},{"id":"tot61-7","nombre":"John White","posicion":"MEI","fuerza":87,"perfil":"playmaker"},{"id":"tot61-8","nombre":"Cliff Jones","posicion":"EXT","fuerza":86,"perfil":"extremo"},{"id":"tot61-9","nombre":"Bobby Smith","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"tot61-10","nombre":"Les Allen","posicion":"CA","fuerza":80,"perfil":"segundo-delantero"},{"id":"tot61-11","nombre":"Terry Dyson","posicion":"PI","fuerza":78,"perfil":"extremo"}]},
  {"id":"leeds-1974","seleccion":"Leeds United","seleccionSlug":"leeds-united","year":1974,"torneo":"Campeón de Liga 1973-74 (era Don Revie)","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"lee74-1","nombre":"David Harvey","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"lee74-2","nombre":"Paul Reaney","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"lee74-3","nombre":"Trevor Cherry","posicion":"LE","fuerza":78,"perfil":"lateral"},{"id":"lee74-4","nombre":"Norman Hunter","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"lee74-5","nombre":"Paul Madeley","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"lee74-6","nombre":"Billy Bremner","posicion":"VOL","fuerza":90,"perfil":"volante"},{"id":"lee74-7","nombre":"Johnny Giles","posicion":"MEI","fuerza":88,"perfil":"playmaker"},{"id":"lee74-8","nombre":"Peter Lorimer","posicion":"EXT","fuerza":85,"perfil":"extremo"},{"id":"lee74-9","nombre":"Eddie Gray","posicion":"EXT","fuerza":85,"perfil":"extremo"},{"id":"lee74-10","nombre":"Allan Clarke","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"lee74-11","nombre":"Mick Jones","posicion":"CA","fuerza":80,"perfil":"goleador"}]},
  {"id":"nottingham-forest-1980","seleccion":"Nottingham Forest","seleccionSlug":"nottingham-forest","year":1980,"torneo":"Bicampeón de Europa 1979-80 (era Brian Clough)","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"nff80-1","nombre":"Peter Shilton","posicion":"GOL","fuerza":90,"perfil":"portero"},{"id":"nff80-2","nombre":"Viv Anderson","posicion":"LD","fuerza":82,"perfil":"lateral"},{"id":"nff80-3","nombre":"Frank Clark","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"nff80-4","nombre":"Larry Lloyd","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"nff80-5","nombre":"Kenny Burns","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"nff80-6","nombre":"John McGovern","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"nff80-7","nombre":"Ian Bowyer","posicion":"VOL","fuerza":78,"perfil":"volante"},{"id":"nff80-8","nombre":"Martin O'Neill","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"nff80-9","nombre":"John Robertson","posicion":"EXT","fuerza":88,"perfil":"extremo"},{"id":"nff80-10","nombre":"Garry Birtles","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"nff80-11","nombre":"Trevor Francis","posicion":"CA","fuerza":86,"perfil":"goleador"}]},
  {"id":"liverpool-1984","seleccion":"Liverpool","seleccionSlug":"liverpool","year":1984,"torneo":"Treble: Liga, Copa de la Liga y Copa de Europa 1984","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"liv84-1","nombre":"Bruce Grobbelaar","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"liv84-2","nombre":"Phil Neal","posicion":"LD","fuerza":82,"perfil":"lateral"},{"id":"liv84-3","nombre":"Alan Kennedy","posicion":"LE","fuerza":79,"perfil":"lateral"},{"id":"liv84-4","nombre":"Mark Lawrenson","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"liv84-5","nombre":"Alan Hansen","posicion":"ZAG","fuerza":86,"perfil":"libero"},{"id":"liv84-6","nombre":"Graeme Souness","posicion":"VOL","fuerza":89,"perfil":"volante"},{"id":"liv84-7","nombre":"Ronnie Whelan","posicion":"MCD","fuerza":82,"perfil":"volante"},{"id":"liv84-8","nombre":"Sammy Lee","posicion":"MCD","fuerza":78,"perfil":"volante"},{"id":"liv84-9","nombre":"Craig Johnston","posicion":"EXT","fuerza":79,"perfil":"extremo"},{"id":"liv84-10","nombre":"Kenny Dalglish","posicion":"CA","fuerza":92,"perfil":"segundo-delantero"},{"id":"liv84-11","nombre":"Ian Rush","posicion":"CA","fuerza":89,"perfil":"goleador"}]},
  {"id":"manchester-united-1999","seleccion":"Manchester United","seleccionSlug":"manchester-united","year":1999,"torneo":"El Triplete 1998-99: Liga, FA Cup y Champions","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"mun99-1","nombre":"Peter Schmeichel","posicion":"GOL","fuerza":89,"perfil":"portero"},{"id":"mun99-2","nombre":"Gary Neville","posicion":"LD","fuerza":82,"perfil":"lateral"},{"id":"mun99-3","nombre":"Denis Irwin","posicion":"LE","fuerza":82,"perfil":"lateral"},{"id":"mun99-4","nombre":"Jaap Stam","posicion":"ZAG","fuerza":86,"perfil":"central"},{"id":"mun99-5","nombre":"Ronny Johnsen","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"mun99-6","nombre":"Roy Keane","posicion":"MCD","fuerza":90,"perfil":"volante"},{"id":"mun99-7","nombre":"Paul Scholes","posicion":"MEI","fuerza":88,"perfil":"playmaker"},{"id":"mun99-8","nombre":"David Beckham","posicion":"EXT","fuerza":87,"perfil":"extremo"},{"id":"mun99-9","nombre":"Ryan Giggs","posicion":"EXT","fuerza":88,"perfil":"extremo"},{"id":"mun99-10","nombre":"Dwight Yorke","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"mun99-11","nombre":"Andy Cole","posicion":"CA","fuerza":83,"perfil":"goleador"}]},
  {"id":"arsenal-2004","seleccion":"Arsenal","seleccionSlug":"arsenal","year":2004,"torneo":"Los Invencibles 2003-04 (invicto en Liga)","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"ars04-1","nombre":"Jens Lehmann","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"ars04-2","nombre":"Lauren","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"ars04-3","nombre":"Ashley Cole","posicion":"LE","fuerza":85,"perfil":"lateral-ofensivo"},{"id":"ars04-4","nombre":"Sol Campbell","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"ars04-5","nombre":"Kolo Touré","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"ars04-6","nombre":"Patrick Vieira","posicion":"MCD","fuerza":89,"perfil":"volante"},{"id":"ars04-7","nombre":"Gilberto Silva","posicion":"MCD","fuerza":82,"perfil":"volante"},{"id":"ars04-8","nombre":"Freddie Ljungberg","posicion":"EXT","fuerza":84,"perfil":"extremo"},{"id":"ars04-9","nombre":"Robert Pirès","posicion":"EXT","fuerza":86,"perfil":"extremo"},{"id":"ars04-10","nombre":"Thierry Henry","posicion":"CA","fuerza":93,"perfil":"goleador"},{"id":"ars04-11","nombre":"Dennis Bergkamp","posicion":"CA","fuerza":89,"perfil":"segundo-delantero"}]},
  {"id":"chelsea-2005","seleccion":"Chelsea","seleccionSlug":"chelsea","year":2005,"torneo":"Campeón de Liga 2004-05 (era Mourinho, récord de puntos)","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"che05-1","nombre":"Petr Čech","posicion":"GOL","fuerza":88,"perfil":"portero"},{"id":"che05-2","nombre":"Paulo Ferreira","posicion":"LD","fuerza":79,"perfil":"lateral"},{"id":"che05-3","nombre":"John Terry","posicion":"ZAG","fuerza":89,"perfil":"central"},{"id":"che05-4","nombre":"Ricardo Carvalho","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"che05-5","nombre":"William Gallas","posicion":"LE","fuerza":83,"perfil":"lateral"},{"id":"che05-6","nombre":"Claude Makélélé","posicion":"MCD","fuerza":87,"perfil":"volante"},{"id":"che05-7","nombre":"Frank Lampard","posicion":"MEI","fuerza":90,"perfil":"playmaker"},{"id":"che05-8","nombre":"Tiago","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"che05-9","nombre":"Arjen Robben","posicion":"PD","fuerza":86,"perfil":"extremo"},{"id":"che05-10","nombre":"Damien Duff","posicion":"PI","fuerza":83,"perfil":"extremo"},{"id":"che05-11","nombre":"Didier Drogba","posicion":"CA","fuerza":86,"perfil":"goleador"}]},
  {"id":"manchester-city-2023","seleccion":"Manchester City","seleccionSlug":"manchester-city","year":2023,"torneo":"El Triplete 2022-23: Liga, FA Cup y Champions","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"mci23-1","nombre":"Ederson","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"mci23-2","nombre":"Kyle Walker","posicion":"LD","fuerza":84,"perfil":"lateral"},{"id":"mci23-3","nombre":"Rúben Dias","posicion":"ZAG","fuerza":87,"perfil":"central"},{"id":"mci23-4","nombre":"Manuel Akanji","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"mci23-5","nombre":"Nathan Aké","posicion":"LE","fuerza":82,"perfil":"lateral"},{"id":"mci23-6","nombre":"Rodri","posicion":"MCD","fuerza":89,"perfil":"volante"},{"id":"mci23-7","nombre":"Kevin De Bruyne","posicion":"MEI","fuerza":92,"perfil":"playmaker"},{"id":"mci23-8","nombre":"İlkay Gündoğan","posicion":"MEI","fuerza":86,"perfil":"mediapunta"},{"id":"mci23-9","nombre":"Bernardo Silva","posicion":"PD","fuerza":87,"perfil":"extremo"},{"id":"mci23-10","nombre":"Jack Grealish","posicion":"PI","fuerza":84,"perfil":"extremo"},{"id":"mci23-11","nombre":"Erling Haaland","posicion":"CA","fuerza":91,"perfil":"goleador"}]},
  {"id":"caracas-fc-2009","seleccion":"Caracas FC","seleccionSlug":"caracas-fc","year":2009,"torneo":"Primera División de Venezuela / Copa Libertadores","bandera":"🇻🇪","liga":"liga-futve","jugadores":[{"id":"sanhouse","nombre":"Manuel Sanhouse","posicion":"GOL","fuerza":77,"perfil":"portero"},{"id":"fuenmayor","nombre":"Juan Fuenmayor","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"jm-rey","nombre":"José Manuel Rey","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"vizcarrondo","nombre":"Oswaldo Vizcarrondo","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"a-cichero","nombre":"Alejandro Cichero","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"lucena","nombre":"Franklin Lucena","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"seijas","nombre":"Luis Manuel Seijas","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"jorge-rojas","nombre":"Jorge Rojas","posicion":"MEI","fuerza":86,"perfil":"playmaker"},{"id":"paez","nombre":"Ricardo Páez","posicion":"PD","fuerza":81,"perfil":"extremo"},{"id":"cesar-gonzalez","nombre":"César González","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"miku","nombre":"Nicolás \"Miku\" Fedor","posicion":"PI","fuerza":82,"perfil":"segundo-delantero"}]},
  {"id":"deportivo-tachira-2010","seleccion":"Deportivo Táchira","seleccionSlug":"deportivo-tachira","year":2010,"torneo":"Primera División de Venezuela / Copa Libertadores (era dorada)","bandera":"🇻🇪","liga":"liga-futve","jugadores":[{"id":"romo","nombre":"Rafael Romo","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"cumana","nombre":"Yohan Cumaná","posicion":"LD","fuerza":71,"perfil":"lateral"},{"id":"perozo","nombre":"Grenddy Perozo","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"chancellor","nombre":"John Chancellor","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"wilker-angel","nombre":"Wilker Ángel","posicion":"LE","fuerza":74,"perfil":"central"},{"id":"anderson-contreras","nombre":"Anderson Contreras","posicion":"MCD","fuerza":77,"perfil":"volante"},{"id":"gerzon-chacon","nombre":"Gerzon Chacón","posicion":"VOL","fuerza":75,"perfil":"volante"},{"id":"urdaneta","nombre":"Gabriel Urdaneta","posicion":"MEI","fuerza":86,"perfil":"playmaker"},{"id":"torrealba","nombre":"José Luis Torrealba","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"digiorgi","nombre":"Giacomo Di Giorgi","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"arismendi","nombre":"Daniel Arismendi","posicion":"PI","fuerza":82,"perfil":"segundo-delantero"}]},
  {"id":"zamora-fc-2013","seleccion":"Zamora FC","seleccionSlug":"zamora-fc","year":2013,"torneo":"Primera División de Venezuela / Copa Libertadores (era dorada)","bandera":"🇻🇪","liga":"liga-futve","jugadores":[{"id":"renny-vega","nombre":"Renny Vega","posicion":"GOL","fuerza":77,"perfil":"portero"},{"id":"ronald-hernandez","nombre":"Ronald Hernández","posicion":"LD","fuerza":72,"perfil":"lateral"},{"id":"jm-velasquez","nombre":"José Manuel Velásquez","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"junior-moreno","nombre":"Junior Moreno","posicion":"ZAG","fuerza":74,"perfil":"central"},{"id":"alexander-gonzalez","nombre":"Alexander González","posicion":"LE","fuerza":74,"perfil":"lateral"},{"id":"romulo-otero","nombre":"Rómulo Otero","posicion":"VOL","fuerza":80,"perfil":"playmaker"},{"id":"del-valle","nombre":"Jonathan Del Valle","posicion":"EXT","fuerza":81,"perfil":"extremo"},{"id":"alejandro-guerra","nombre":"Alejandro Guerra","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"orozco","nombre":"Yohandry Orozco","posicion":"EXT","fuerza":84,"perfil":"extremo"},{"id":"falcon","nombre":"Juan Falcón","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"gelmin-rivas","nombre":"Gelmin Rivas","posicion":"PI","fuerza":76,"perfil":"segundo-delantero"}]},
  {"id":"atletico-nacional-1989","seleccion":"Atlético Nacional","seleccionSlug":"atletico-nacional","year":1989,"torneo":"Copa Libertadores 1989 (campeón)","bandera":"🇨🇴","liga":"primera-a-colombia","jugadores":[{"id":"higuita","nombre":"René Higuita","posicion":"GOL","fuerza":89,"perfil":"portero"},{"id":"carmona","nombre":"John Jairo Carmona","posicion":"LD","fuerza":73,"perfil":"lateral"},{"id":"luis-carlos-perea","nombre":"Luis Carlos Perea","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"andres-escobar","nombre":"Andrés Escobar","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"gildardo-gomez","nombre":"Gildardo Gómez","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"leonel-alvarez","nombre":"Leonel Álvarez","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"alexis-garcia","nombre":"Alexis García","posicion":"MEI","fuerza":81,"perfil":"playmaker"},{"id":"luis-fajardo","nombre":"Luis Fajardo","posicion":"VOL","fuerza":74,"perfil":"volante"},{"id":"jaime-arango","nombre":"Jaime Arango","posicion":"EXT","fuerza":73,"perfil":"extremo"},{"id":"usuriaga","nombre":"Albeiro Usuriaga","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"trellez","nombre":"John Jairo Tréllez","posicion":"CA","fuerza":79,"perfil":"goleador"}]},
  {"id":"millonarios-2023","seleccion":"Millonarios","seleccionSlug":"millonarios","year":2023,"torneo":"Liga BetPlay 2023-I (campeón)","bandera":"🇨🇴","liga":"primera-a-colombia","jugadores":[{"id":"montero","nombre":"Álvaro Montero","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"perlaza","nombre":"Elvis Perlaza","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"llinas","nombre":"Andrés Llinás","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"jorge-arias","nombre":"Jorge Arias","posicion":"ZAG","fuerza":75,"perfil":"central"},{"id":"bertel","nombre":"Omar Bertel","posicion":"LE","fuerza":72,"perfil":"lateral"},{"id":"stiven-vega","nombre":"Stiven Vega","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"giraldo","nombre":"Daniel Giraldo","posicion":"VOL","fuerza":74,"perfil":"volante"},{"id":"catano","nombre":"Daniel Cataño","posicion":"MEI","fuerza":79,"perfil":"mediapunta"},{"id":"mackalister-silva","nombre":"David Mackalister Silva","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"oscar-cortes","nombre":"Óscar Cortés","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"leonardo-castro","nombre":"Leonardo Castro","posicion":"CA","fuerza":81,"perfil":"goleador"}]},
  {"id":"america-de-cali-1986","seleccion":"América de Cali","seleccionSlug":"america-de-cali","year":1986,"torneo":"Copa Libertadores 1986 (finalista, era dorada)","bandera":"🇨🇴","liga":"primera-a-colombia","jugadores":[{"id":"falcioni","nombre":"Julio César Falcioni","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"hugo-valencia","nombre":"Hugo Valencia","posicion":"LD","fuerza":73,"perfil":"lateral"},{"id":"victor-espinosa","nombre":"Víctor Espinosa","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"esterilla","nombre":"Enrique Esterilla","posicion":"ZAG","fuerza":73,"perfil":"central"},{"id":"porras","nombre":"Jorge Porras","posicion":"LE","fuerza":74,"perfil":"lateral"},{"id":"gonzalez-aquino","nombre":"Gerardo González Aquino","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"ischia","nombre":"Carlos Ischia","posicion":"MEI","fuerza":78,"perfil":"playmaker"},{"id":"battaglia","nombre":"Juan Manuel Battaglia","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"willington-ortiz","nombre":"Willington Ortiz","posicion":"PI","fuerza":87,"perfil":"extremo"},{"id":"cabanas","nombre":"Roberto Cabañas","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"gareca","nombre":"Ricardo Gareca","posicion":"CA","fuerza":84,"perfil":"goleador"}]},
];

// Copas continentales → ligas DOMÉSTICAS cuyos clubes las disputan. Así, quien
// sigue "Libertadores" draftea clubes de Sudamérica; quien sigue "Champions",
// de las grandes de Europa.
const CONTINENTAL_MAP: Record<string, string[]> = {
  libertadores: ["liga-argentina", "brasileirao", "ligapro-ecuador", "primera-a-colombia", "liga-futve", "liga-mx"],
  sudamericana: ["liga-argentina", "brasileirao", "ligapro-ecuador", "primera-a-colombia", "liga-futve"],
  "champions-league": ["laliga", "premier-league", "serie-a", "bundesliga", "ligue-1", "primeira-liga"],
  "europa-league": ["laliga", "premier-league", "serie-a", "bundesliga", "ligue-1", "primeira-liga"],
  "conference-league": ["laliga", "premier-league", "serie-a", "bundesliga", "ligue-1", "primeira-liga"],
  "concacaf-champions": ["liga-mx", "mls"],
};

/**
 * Pool de plantillas de clubes para las ligas seguidas por el usuario. Expande
 * las copas continentales a sus ligas domésticas. Fallbacks encadenados para no
 * dejar NUNCA un pool vacío (el motor haría crash):
 *   1) clubes de las ligas del usuario (si hay ≥2),
 *   2) todos los clubes,
 *   3) las selecciones históricas (si aún no hay clubes cargados).
 */
export function poolForLeagues(slugs: string[]): DraftPlantilla[] {
  if (CLUB_PLANTILLAS.length === 0) return PLANTILLAS;
  if (!slugs || slugs.length === 0) return CLUB_PLANTILLAS;
  const wanted = new Set<string>();
  for (const s of slugs) {
    wanted.add(s);
    for (const d of CONTINENTAL_MAP[s] ?? []) wanted.add(d);
  }
  const filtered = CLUB_PLANTILLAS.filter((p) => p.liga && wanted.has(p.liga));
  return filtered.length >= 2 ? filtered : CLUB_PLANTILLAS;
}

/** Slugs de liga que aporta un slug (él mismo + su expansión continental). */
function expand(slug: string): Set<string> {
  return new Set<string>([slug, ...(CONTINENTAL_MAP[slug] ?? [])]);
}

/** ¿Esa liga (o copa continental) tiene al menos un club en el catálogo? */
export function leagueHasClubs(slug: string): boolean {
  const wanted = expand(slug);
  return CLUB_PLANTILLAS.some((p) => !!p.liga && wanted.has(p.liga));
}

/**
 * Pool de UNA sola liga (la elegida por el usuario en el Draft): solo clubes de
 * esa liga/copa. NUNCA mezcla otras ligas ni cae a selecciones históricas si hay
 * clubes cargados (si la liga no tuviera clubes, cae a todos los clubes, jamás al
 * Mundial). Así "elijo España → solo España".
 */
export function poolForLeague(slug: string): DraftPlantilla[] {
  if (CLUB_PLANTILLAS.length === 0) return PLANTILLAS;
  const wanted = expand(slug);
  const filtered = CLUB_PLANTILLAS.filter((p) => !!p.liga && wanted.has(p.liga));
  return filtered.length >= 2 ? filtered : CLUB_PLANTILLAS;
}

export interface DraftLeagueOption { slug: string; short: string; }

/** Ligas del catálogo que tienen clubes drafteables (para el selector). */
export const DRAFT_LEAGUES: DraftLeagueOption[] = Array.from(
  new Set(CLUB_PLANTILLAS.map((p) => p.liga).filter((s): s is string => !!s)),
).map((slug) => ({ slug, short: getCompetition(slug)?.short ?? slug }));

/**
 * Ligas ENTRE LAS QUE PUEDE ELEGIR el usuario en el Draft: las que sigue y que
 * tienen clubes (directas o vía copa continental). Si no sigue ninguna con
 * clubes, ofrecemos todas las disponibles (para que el Draft siga jugable).
 */
export function availableDraftLeagues(followed: string[]): DraftLeagueOption[] {
  const opts: DraftLeagueOption[] = [];
  const seen = new Set<string>();
  for (const slug of followed ?? []) {
    if (seen.has(slug) || !leagueHasClubs(slug)) continue;
    seen.add(slug);
    opts.push({ slug, short: getCompetition(slug)?.short ?? slug });
  }
  return opts.length > 0 ? opts : DRAFT_LEAGUES;
}
