// src/lib/draft/plantillas.ts
// 34 plantillas históricas emblemáticas de Copas del Mundo (varias ediciones
// con 2-3 selecciones para que "Otra selección" / "Otro mundial" tengan sentido)

import { DraftPlantilla } from "./types";

export const PLANTILLAS: DraftPlantilla[] = [
  {
    id: "bra-1970",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 1970,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b70-1", nombre: "Pelé", posicion: "CA", fuerza: 97, perfil: "goleador" },
      { id: "b70-2", nombre: "Gérson", posicion: "MEI", fuerza: 89, perfil: "playmaker" },
      { id: "b70-3", nombre: "Rivelino", posicion: "PI", fuerza: 90, perfil: "extremo" },
      { id: "b70-4", nombre: "Jairzinho", posicion: "PD", fuerza: 91, perfil: "extremo" },
      { id: "b70-5", nombre: "Tostão", posicion: "CA", fuerza: 88, perfil: "segundo-delantero" },
      { id: "b70-6", nombre: "Clodoaldo", posicion: "VOL", fuerza: 85, perfil: "volante" },
      { id: "b70-7", nombre: "Carlos Alberto", posicion: "LD", fuerza: 90, perfil: "lateral-ofensivo" },
      { id: "b70-8", nombre: "Everaldo", posicion: "LE", fuerza: 84, perfil: "lateral" },
      { id: "b70-9", nombre: "Britto", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "b70-10", nombre: "Piazza", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "b70-11", nombre: "Félix", posicion: "GOL", fuerza: 83, perfil: "portero" },
    ],
  },
  {
    id: "arg-1986",
    seleccion: "Argentina",
    seleccionSlug: "argentina",
    year: 1986,
    torneo: "Copa del Mundo",
    bandera: "🇦🇷",
    jugadores: [
      { id: "a86-1", nombre: "Maradona", posicion: "MEI", fuerza: 98, perfil: "playmaker" },
      { id: "a86-2", nombre: "Valdano", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "a86-3", nombre: "Burruchaga", posicion: "MEI", fuerza: 88, perfil: "extremo" },
      { id: "a86-4", nombre: "Enrique", posicion: "PD", fuerza: 85, perfil: "extremo" },
      { id: "a86-5", nombre: "Giusti", posicion: "VOL", fuerza: 86, perfil: "volante" },
      { id: "a86-6", nombre: "Batista", posicion: "MCD", fuerza: 84, perfil: "volante" },
      { id: "a86-7", nombre: "Ruggeri", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "a86-8", nombre: "Brown", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "a86-9", nombre: "Cuciuffo", posicion: "LD", fuerza: 84, perfil: "lateral" },
      { id: "a86-10", nombre: "Pumpido", posicion: "GOL", fuerza: 86, perfil: "portero" },
      { id: "a86-11", nombre: "Trobbiani", posicion: "MEI", fuerza: 82, perfil: "mediapunta" },
    ],
  },
  {
    id: "ale-1974",
    seleccion: "Alemania",
    seleccionSlug: "alemania",
    year: 1974,
    torneo: "Copa del Mundo",
    bandera: "🇩🇪",
    jugadores: [
      { id: "a74-1", nombre: "Beckenbauer", posicion: "ZAG", fuerza: 96, perfil: "libero" },
      { id: "a74-2", nombre: "Müller", posicion: "CA", fuerza: 94, perfil: "goleador" },
      { id: "a74-3", nombre: "Overath", posicion: "MEI", fuerza: 89, perfil: "playmaker" },
      { id: "a74-4", nombre: "Breitner", posicion: "LD", fuerza: 88, perfil: "lateral-ofensivo" },
      { id: "a74-5", nombre: "Hoeness", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "a74-6", nombre: "Grabowski", posicion: "EXT", fuerza: 85, perfil: "extremo" },
      { id: "a74-7", nombre: "Schwarzenbeck", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "a74-8", nombre: "Vogts", posicion: "LD", fuerza: 87, perfil: "lateral" },
      { id: "a74-9", nombre: "Bonhof", posicion: "MEI", fuerza: 86, perfil: "volante" },
      { id: "a74-10", nombre: "Flohe", posicion: "VOL", fuerza: 84, perfil: "volante" },
      { id: "a74-11", nombre: "Maier", posicion: "GOL", fuerza: 91, perfil: "portero" },
    ],
  },
  {
    id: "hol-1974",
    seleccion: "Holanda",
    seleccionSlug: "holanda",
    year: 1974,
    torneo: "Copa del Mundo",
    bandera: "🇳🇱",
    jugadores: [
      { id: "h74-1", nombre: "Cruyff", posicion: "CA", fuerza: 97, perfil: "falso-nueve" },
      { id: "h74-2", nombre: "Neeskens", posicion: "VOL", fuerza: 91, perfil: "volante" },
      { id: "h74-3", nombre: "Rep", posicion: "EXT", fuerza: 89, perfil: "extremo" },
      { id: "h74-4", nombre: "Rensenbrink", posicion: "PI", fuerza: 88, perfil: "extremo" },
      { id: "h74-5", nombre: "Haan", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "h74-6", nombre: "Krol", posicion: "LE", fuerza: 89, perfil: "lateral" },
      { id: "h74-7", nombre: "Suurbier", posicion: "LD", fuerza: 86, perfil: "lateral" },
      { id: "h74-8", nombre: "Jansen", posicion: "VOL", fuerza: 85, perfil: "volante" },
      { id: "h74-9", nombre: "Rijsbergen", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "h74-10", nombre: "Van Hanegem", posicion: "MEI", fuerza: 88, perfil: "playmaker" },
      { id: "h74-11", nombre: "Jongbloed", posicion: "GOL", fuerza: 84, perfil: "portero" },
    ],
  },
  {
    id: "fra-1998",
    seleccion: "Francia",
    seleccionSlug: "francia",
    year: 1998,
    torneo: "Copa del Mundo",
    bandera: "🇫🇷",
    jugadores: [
      { id: "f98-1", nombre: "Zidane", posicion: "MEI", fuerza: 96, perfil: "playmaker" },
      { id: "f98-2", nombre: "Henry", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "f98-3", nombre: "Djorkaeff", posicion: "MEI", fuerza: 88, perfil: "mediapunta" },
      { id: "f98-4", nombre: "Deschamps", posicion: "MCD", fuerza: 88, perfil: "volante" },
      { id: "f98-5", nombre: "Petit", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "f98-6", nombre: "Barthez", posicion: "GOL", fuerza: 89, perfil: "portero" },
      { id: "f98-7", nombre: "Thuram", posicion: "LD", fuerza: 90, perfil: "lateral" },
      { id: "f98-8", nombre: "Blanc", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "f98-9", nombre: "Desailly", posicion: "ZAG", fuerza: 90, perfil: "central" },
      { id: "f98-10", nombre: "Lizarazu", posicion: "LE", fuerza: 88, perfil: "lateral" },
      { id: "f98-11", nombre: "Trezeguet", posicion: "CA", fuerza: 87, perfil: "goleador" },
    ],
  },
  {
    id: "esp-2010",
    seleccion: "España",
    seleccionSlug: "espana",
    year: 2010,
    torneo: "Copa del Mundo",
    bandera: "🇪🇸",
    jugadores: [
      { id: "e10-1", nombre: "Iniesta", posicion: "MEI", fuerza: 95, perfil: "playmaker" },
      { id: "e10-2", nombre: "Xavi", posicion: "VOL", fuerza: 95, perfil: "playmaker" },
      { id: "e10-3", nombre: "Villa", posicion: "CA", fuerza: 92, perfil: "goleador" },
      { id: "e10-4", nombre: "Xabi Alonso", posicion: "MCD", fuerza: 90, perfil: "volante" },
      { id: "e10-5", nombre: "Busquets", posicion: "MCD", fuerza: 89, perfil: "volante" },
      { id: "e10-6", nombre: "Casillas", posicion: "GOL", fuerza: 92, perfil: "portero" },
      { id: "e10-7", nombre: "Piqué", posicion: "ZAG", fuerza: 90, perfil: "central" },
      { id: "e10-8", nombre: "Puyol", posicion: "ZAG", fuerza: 91, perfil: "central" },
      { id: "e10-9", nombre: "Ramos", posicion: "LD", fuerza: 90, perfil: "lateral" },
      { id: "e10-10", nombre: "Capdevila", posicion: "LE", fuerza: 85, perfil: "lateral" },
      { id: "e10-11", nombre: "Pedro", posicion: "EXT", fuerza: 87, perfil: "extremo" },
    ],
  },
  {
    id: "bra-2002",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 2002,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b02-1", nombre: "Ronaldo", posicion: "CA", fuerza: 96, perfil: "goleador" },
      { id: "b02-2", nombre: "Rivaldo", posicion: "PI", fuerza: 93, perfil: "extremo" },
      { id: "b02-3", nombre: "Ronaldinho", posicion: "MEI", fuerza: 94, perfil: "playmaker" },
      { id: "b02-4", nombre: "Cafu", posicion: "LD", fuerza: 90, perfil: "lateral-ofensivo" },
      { id: "b02-5", nombre: "Roberto Carlos", posicion: "LE", fuerza: 91, perfil: "lateral-ofensivo" },
      { id: "b02-6", nombre: "Gilberto Silva", posicion: "MCD", fuerza: 88, perfil: "volante" },
      { id: "b02-7", nombre: "Kléberson", posicion: "VOL", fuerza: 85, perfil: "volante" },
      { id: "b02-8", nombre: "Lucio", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "b02-9", nombre: "Roque Junior", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "b02-10", nombre: "Edmílson", posicion: "VOL", fuerza: 86, perfil: "volante" },
      { id: "b02-11", nombre: "Marcos", posicion: "GOL", fuerza: 87, perfil: "portero" },
    ],
  },
  {
    id: "ita-1982",
    seleccion: "Italia",
    seleccionSlug: "italia",
    year: 1982,
    torneo: "Copa del Mundo",
    bandera: "🇮🇹",
    jugadores: [
      { id: "i82-1", nombre: "Rossi", posicion: "CA", fuerza: 93, perfil: "goleador" },
      { id: "i82-2", nombre: "Conti", posicion: "MEI", fuerza: 89, perfil: "playmaker" },
      { id: "i82-3", nombre: "Tardelli", posicion: "VOL", fuerza: 90, perfil: "volante" },
      { id: "i82-4", nombre: "Gentile", posicion: "LD", fuerza: 88, perfil: "lateral" },
      { id: "i82-5", nombre: "Scirea", posicion: "ZAG", fuerza: 91, perfil: "libero" },
      { id: "i82-6", nombre: "Cabrini", posicion: "LE", fuerza: 88, perfil: "lateral" },
      { id: "i82-7", nombre: "Oriali", posicion: "VOL", fuerza: 86, perfil: "volante" },
      { id: "i82-8", nombre: "Antognoni", posicion: "MEI", fuerza: 89, perfil: "playmaker" },
      { id: "i82-9", nombre: "Graziani", posicion: "CA", fuerza: 87, perfil: "goleador" },
      { id: "i82-10", nombre: "Collovati", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "i82-11", nombre: "Zoff", posicion: "GOL", fuerza: 91, perfil: "portero" },
    ],
  },
  {
    id: "ale-2014",
    seleccion: "Alemania",
    seleccionSlug: "alemania",
    year: 2014,
    torneo: "Copa del Mundo",
    bandera: "🇩🇪",
    jugadores: [
      { id: "a14-1", nombre: "Müller", posicion: "CA", fuerza: 92, perfil: "goleador" },
      { id: "a14-2", nombre: "Kroos", posicion: "VOL", fuerza: 92, perfil: "playmaker" },
      { id: "a14-3", nombre: "Özil", posicion: "MEI", fuerza: 91, perfil: "playmaker" },
      { id: "a14-4", nombre: "Schweinsteiger", posicion: "MCD", fuerza: 90, perfil: "volante" },
      { id: "a14-5", nombre: "Klose", posicion: "CA", fuerza: 89, perfil: "goleador" },
      { id: "a14-6", nombre: "Neuer", posicion: "GOL", fuerza: 94, perfil: "portero" },
      { id: "a14-7", nombre: "Hummels", posicion: "ZAG", fuerza: 91, perfil: "central" },
      { id: "a14-8", nombre: "Boateng", posicion: "ZAG", fuerza: 90, perfil: "central" },
      { id: "a14-9", nombre: "Lahm", posicion: "LD", fuerza: 91, perfil: "lateral" },
      { id: "a14-10", nombre: "Schürrle", posicion: "EXT", fuerza: 88, perfil: "extremo" },
      { id: "a14-11", nombre: "Höwedes", posicion: "LE", fuerza: 87, perfil: "lateral" },
    ],
  },
  {
    id: "arg-2022",
    seleccion: "Argentina",
    seleccionSlug: "argentina",
    year: 2022,
    torneo: "Copa del Mundo",
    bandera: "🇦🇷",
    jugadores: [
      { id: "a22-1", nombre: "Messi", posicion: "CA", fuerza: 97, perfil: "playmaker" },
      { id: "a22-2", nombre: "Álvarez", posicion: "CA", fuerza: 89, perfil: "goleador" },
      { id: "a22-3", nombre: "Di María", posicion: "EXT", fuerza: 90, perfil: "extremo" },
      { id: "a22-4", nombre: "De Paul", posicion: "VOL", fuerza: 90, perfil: "volante" },
      { id: "a22-5", nombre: "Enzo", posicion: "MCD", fuerza: 89, perfil: "volante" },
      { id: "a22-6", nombre: "Mac Allister", posicion: "MEI", fuerza: 88, perfil: "playmaker" },
      { id: "a22-7", nombre: "Otamendi", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "a22-8", nombre: "Romero", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "a22-9", nombre: "Molina", posicion: "LD", fuerza: 88, perfil: "lateral" },
      { id: "a22-10", nombre: "Tagliafico", posicion: "LE", fuerza: 87, perfil: "lateral" },
      { id: "a22-11", nombre: "Martínez", posicion: "GOL", fuerza: 91, perfil: "portero" },
    ],
  },
  {
    id: "fra-2018",
    seleccion: "Francia",
    seleccionSlug: "francia",
    year: 2018,
    torneo: "Copa del Mundo",
    bandera: "🇫🇷",
    jugadores: [
      { id: "f18-1", nombre: "Mbappé", posicion: "CA", fuerza: 94, perfil: "goleador" },
      { id: "f18-2", nombre: "Griezmann", posicion: "MEI", fuerza: 92, perfil: "mediapunta" },
      { id: "f18-3", nombre: "Pogba", posicion: "VOL", fuerza: 91, perfil: "playmaker" },
      { id: "f18-4", nombre: "Kanté", posicion: "MCD", fuerza: 93, perfil: "volante" },
      { id: "f18-5", nombre: "Matuidi", posicion: "VOL", fuerza: 88, perfil: "volante" },
      { id: "f18-6", nombre: "Lloris", posicion: "GOL", fuerza: 90, perfil: "portero" },
      { id: "f18-7", nombre: "Varane", posicion: "ZAG", fuerza: 91, perfil: "central" },
      { id: "f18-8", nombre: "Umtiti", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "f18-9", nombre: "Pavard", posicion: "LD", fuerza: 87, perfil: "lateral" },
      { id: "f18-10", nombre: "Hernández", posicion: "LE", fuerza: 88, perfil: "lateral" },
      { id: "f18-11", nombre: "Giroud", posicion: "CA", fuerza: 88, perfil: "goleador" },
    ],
  },
  {
    id: "uru-1950",
    seleccion: "Uruguay",
    seleccionSlug: "uruguay",
    year: 1950,
    torneo: "Copa del Mundo",
    bandera: "🇺🇾",
    jugadores: [
      { id: "u50-1", nombre: "Ghiggia", posicion: "PD", fuerza: 92, perfil: "extremo" },
      { id: "u50-2", nombre: "Schiaffino", posicion: "CA", fuerza: 93, perfil: "goleador" },
      { id: "u50-3", nombre: "Míguez", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "u50-4", nombre: "Varela", posicion: "MCD", fuerza: 91, perfil: "volante" },
      { id: "u50-5", nombre: "Andrade", posicion: "ZAG", fuerza: 90, perfil: "central" },
      { id: "u50-6", nombre: "Gambetta", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "u50-7", nombre: "González", posicion: "LE", fuerza: 86, perfil: "lateral" },
      { id: "u50-8", nombre: "Morán", posicion: "LD", fuerza: 85, perfil: "lateral" },
      { id: "u50-9", nombre: "Pérez", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "u50-10", nombre: "Rijo", posicion: "MEI", fuerza: 86, perfil: "playmaker" },
      { id: "u50-11", nombre: "Máspoli", posicion: "GOL", fuerza: 89, perfil: "portero" },
    ],
  },
  {
    id: "hun-1954",
    seleccion: "Hungría",
    seleccionSlug: "hungria",
    year: 1954,
    torneo: "Copa del Mundo",
    bandera: "🇭🇺",
    jugadores: [
      { id: "h54-1", nombre: "Puskás", posicion: "CA", fuerza: 96, perfil: "goleador" },
      { id: "h54-2", nombre: "Kocsis", posicion: "CA", fuerza: 94, perfil: "goleador" },
      { id: "h54-3", nombre: "Hidegkuti", posicion: "MEI", fuerza: 92, perfil: "falso-nueve" },
      { id: "h54-4", nombre: "Czibor", posicion: "PI", fuerza: 90, perfil: "extremo" },
      { id: "h54-5", nombre: "Bozsik", posicion: "VOL", fuerza: 91, perfil: "playmaker" },
      { id: "h54-6", nombre: "Lantos", posicion: "LD", fuerza: 88, perfil: "lateral" },
      { id: "h54-7", nombre: "Budai", posicion: "LE", fuerza: 87, perfil: "lateral" },
      { id: "h54-8", nombre: "Lóránt", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "h54-9", nombre: "Buzánszky", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "h54-10", nombre: "Zakariás", posicion: "MCD", fuerza: 88, perfil: "volante" },
      { id: "h54-11", nombre: "Grosics", posicion: "GOL", fuerza: 90, perfil: "portero" },
    ],
  },
  {
    id: "ing-1966",
    seleccion: "Inglaterra",
    seleccionSlug: "inglaterra",
    year: 1966,
    torneo: "Copa del Mundo",
    bandera: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    jugadores: [
      { id: "i66-1", nombre: "Charlton", posicion: "MEI", fuerza: 93, perfil: "playmaker" },
      { id: "i66-2", nombre: "Hurst", posicion: "CA", fuerza: 91, perfil: "goleador" },
      { id: "i66-3", nombre: "Banks", posicion: "GOL", fuerza: 93, perfil: "portero" },
      { id: "i66-4", nombre: "Moore", posicion: "ZAG", fuerza: 93, perfil: "central" },
      { id: "i66-5", nombre: "Ball", posicion: "VOL", fuerza: 90, perfil: "volante" },
      { id: "i66-6", nombre: "Stiles", posicion: "MCD", fuerza: 88, perfil: "volante" },
      { id: "i66-7", nombre: "Cohen", posicion: "LD", fuerza: 87, perfil: "lateral" },
      { id: "i66-8", nombre: "Wilson", posicion: "LE", fuerza: 86, perfil: "lateral" },
      { id: "i66-9", nombre: "J. Charlton", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "i66-10", nombre: "Peters", posicion: "EXT", fuerza: 88, perfil: "extremo" },
      { id: "i66-11", nombre: "Hunt", posicion: "CA", fuerza: 89, perfil: "goleador" },
    ],
  },
  {
    id: "ita-1990",
    seleccion: "Italia",
    seleccionSlug: "italia",
    year: 1990,
    torneo: "Copa del Mundo",
    bandera: "🇮🇹",
    jugadores: [
      { id: "i90-1", nombre: "Schillaci", posicion: "CA", fuerza: 91, perfil: "goleador" },
      { id: "i90-2", nombre: "Baggio", posicion: "MEI", fuerza: 93, perfil: "playmaker" },
      { id: "i90-3", nombre: "Vialli", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "i90-4", nombre: "Giannini", posicion: "VOL", fuerza: 89, perfil: "playmaker" },
      { id: "i90-5", nombre: "De Napoli", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "i90-6", nombre: "Zenga", posicion: "GOL", fuerza: 90, perfil: "portero" },
      { id: "i90-7", nombre: "Baresi", posicion: "ZAG", fuerza: 94, perfil: "central" },
      { id: "i90-8", nombre: "Ferri", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "i90-9", nombre: "Bergomi", posicion: "LD", fuerza: 89, perfil: "lateral" },
      { id: "i90-10", nombre: "Maldini", posicion: "LE", fuerza: 91, perfil: "lateral" },
      { id: "i90-11", nombre: "Donadoni", posicion: "EXT", fuerza: 89, perfil: "extremo" },
    ],
  },
  {
    id: "bra-1994",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 1994,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b94-1", nombre: "Romário", posicion: "CA", fuerza: 95, perfil: "goleador" },
      { id: "b94-2", nombre: "Bebeto", posicion: "CA", fuerza: 91, perfil: "goleador" },
      { id: "b94-3", nombre: "Dunga", posicion: "MCD", fuerza: 89, perfil: "volante" },
      { id: "b94-4", nombre: "Mauro Silva", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "b94-5", nombre: "Zinho", posicion: "MEI", fuerza: 88, perfil: "extremo" },
      { id: "b94-6", nombre: "Mazinho", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "b94-7", nombre: "Jorginho", posicion: "LD", fuerza: 88, perfil: "lateral" },
      { id: "b94-8", nombre: "Branco", posicion: "LE", fuerza: 87, perfil: "lateral" },
      { id: "b94-9", nombre: "Aldair", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "b94-10", nombre: "Márcio Santos", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "b94-11", nombre: "Taffarel", posicion: "GOL", fuerza: 89, perfil: "portero" },
    ],
  },
  {
    id: "ale-1990",
    seleccion: "Alemania",
    seleccionSlug: "alemania",
    year: 1990,
    torneo: "Copa del Mundo",
    bandera: "🇩🇪",
    jugadores: [
      { id: "a90-1", nombre: "Matthäus", posicion: "VOL", fuerza: 94, perfil: "playmaker" },
      { id: "a90-2", nombre: "Völler", posicion: "CA", fuerza: 91, perfil: "goleador" },
      { id: "a90-3", nombre: "Klinsmann", posicion: "CA", fuerza: 91, perfil: "goleador" },
      { id: "a90-4", nombre: "Brehme", posicion: "LE", fuerza: 91, perfil: "lateral-ofensivo" },
      { id: "a90-5", nombre: "Kohler", posicion: "ZAG", fuerza: 90, perfil: "central" },
      { id: "a90-6", nombre: "Augenthaler", posicion: "ZAG", fuerza: 89, perfil: "central" },
      { id: "a90-7", nombre: "Reuter", posicion: "LD", fuerza: 88, perfil: "lateral" },
      { id: "a90-8", nombre: "Häßler", posicion: "MEI", fuerza: 89, perfil: "mediapunta" },
      { id: "a90-9", nombre: "Lothar", posicion: "VOL", fuerza: 88, perfil: "volante" },
      { id: "a90-10", nombre: "Thon", posicion: "MEI", fuerza: 88, perfil: "playmaker" },
      { id: "a90-11", nombre: "Illgner", posicion: "GOL", fuerza: 89, perfil: "portero" },
    ],
  },
  {
    id: "arg-1978",
    seleccion: "Argentina",
    seleccionSlug: "argentina",
    year: 1978,
    torneo: "Copa del Mundo",
    bandera: "🇦🇷",
    jugadores: [
      { id: "a78-1", nombre: "Kempes", posicion: "CA", fuerza: 94, perfil: "goleador" },
      { id: "a78-2", nombre: "Luque", posicion: "CA", fuerza: 89, perfil: "goleador" },
      { id: "a78-3", nombre: "Gallego", posicion: "VOL", fuerza: 88, perfil: "volante" },
      { id: "a78-4", nombre: "Ortiz", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "a78-5", nombre: "Tarantini", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "a78-6", nombre: "Passarella", posicion: "ZAG", fuerza: 91, perfil: "central" },
      { id: "a78-7", nombre: "Olguín", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "a78-8", nombre: "Galván", posicion: "LD", fuerza: 86, perfil: "lateral" },
      { id: "a78-9", nombre: "Tagliani", posicion: "LE", fuerza: 85, perfil: "lateral" },
      { id: "a78-10", nombre: "Bertoni", posicion: "EXT", fuerza: 88, perfil: "extremo" },
      { id: "a78-11", nombre: "Fillol", posicion: "GOL", fuerza: 90, perfil: "portero" },
    ],
  },
  {
    id: "ita-2006",
    seleccion: "Italia",
    seleccionSlug: "italia",
    year: 2006,
    torneo: "Copa del Mundo",
    bandera: "🇮🇹",
    jugadores: [
      { id: "i06-1", nombre: "Totti", posicion: "MEI", fuerza: 93, perfil: "playmaker" },
      { id: "i06-2", nombre: "Pirlo", posicion: "VOL", fuerza: 94, perfil: "playmaker" },
      { id: "i06-3", nombre: "Del Piero", posicion: "PI", fuerza: 91, perfil: "extremo" },
      { id: "i06-4", nombre: "Gattuso", posicion: "MCD", fuerza: 91, perfil: "volante" },
      { id: "i06-5", nombre: "Cannavaro", posicion: "ZAG", fuerza: 93, perfil: "central" },
      { id: "i06-6", nombre: "Buffon", posicion: "GOL", fuerza: 94, perfil: "portero" },
      { id: "i06-7", nombre: "Zambrotta", posicion: "LD", fuerza: 90, perfil: "lateral" },
      { id: "i06-8", nombre: "Grosso", posicion: "LE", fuerza: 89, perfil: "lateral" },
      { id: "i06-9", nombre: "Materazzi", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "i06-10", nombre: "Toni", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "i06-11", nombre: "Perrotta", posicion: "VOL", fuerza: 87, perfil: "volante" },
    ],
  },
  {
    id: "por-1966",
    seleccion: "Portugal",
    seleccionSlug: "portugal",
    year: 1966,
    torneo: "Copa del Mundo",
    bandera: "🇵🇹",
    jugadores: [
      { id: "p66-1", nombre: "Eusébio", posicion: "CA", fuerza: 95, perfil: "goleador" },
      { id: "p66-2", nombre: "Torres", posicion: "VOL", fuerza: 88, perfil: "volante" },
      { id: "p66-3", nombre: "Simões", posicion: "EXT", fuerza: 88, perfil: "extremo" },
      { id: "p66-4", nombre: "Coluna", posicion: "MEI", fuerza: 89, perfil: "playmaker" },
      { id: "p66-5", nombre: "Morais", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "p66-6", nombre: "Pereira", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "p66-7", nombre: "Baptista", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "p66-8", nombre: "Hilario", posicion: "LD", fuerza: 86, perfil: "lateral" },
      { id: "p66-9", nombre: "Augusto", posicion: "LE", fuerza: 86, perfil: "lateral" },
      { id: "p66-10", nombre: "Lourenço", posicion: "PI", fuerza: 87, perfil: "extremo" },
      { id: "p66-11", nombre: "José Pereira", posicion: "GOL", fuerza: 88, perfil: "portero" },
    ],
  },
  {
    id: "bra-1958",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 1958,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b58-1", nombre: "Pelé", posicion: "CA", fuerza: 94, perfil: "goleador" },
      { id: "b58-2", nombre: "Garrincha", posicion: "PD", fuerza: 95, perfil: "extremo" },
      { id: "b58-3", nombre: "Vavá", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "b58-4", nombre: "Didi", posicion: "MEI", fuerza: 92, perfil: "playmaker" },
      { id: "b58-5", nombre: "Zagallo", posicion: "PI", fuerza: 87, perfil: "extremo" },
      { id: "b58-6", nombre: "Zito", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "b58-7", nombre: "Nílton Santos", posicion: "LE", fuerza: 90, perfil: "lateral" },
      { id: "b58-8", nombre: "Djalma Santos", posicion: "LD", fuerza: 88, perfil: "lateral" },
      { id: "b58-9", nombre: "Bellini", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "b58-10", nombre: "Orlando", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "b58-11", nombre: "Gilmar", posicion: "GOL", fuerza: 89, perfil: "portero" },
    ],
  },
  {
    id: "bra-1962",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 1962,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b62-1", nombre: "Garrincha", posicion: "PD", fuerza: 96, perfil: "extremo" },
      { id: "b62-2", nombre: "Vavá", posicion: "CA", fuerza: 89, perfil: "goleador" },
      { id: "b62-3", nombre: "Amarildo", posicion: "CA", fuerza: 87, perfil: "goleador" },
      { id: "b62-4", nombre: "Didi", posicion: "MEI", fuerza: 90, perfil: "playmaker" },
      { id: "b62-5", nombre: "Zagallo", posicion: "PI", fuerza: 86, perfil: "extremo" },
      { id: "b62-6", nombre: "Zito", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "b62-7", nombre: "Nílton Santos", posicion: "LE", fuerza: 89, perfil: "lateral" },
      { id: "b62-8", nombre: "Djalma Santos", posicion: "LD", fuerza: 87, perfil: "lateral" },
      { id: "b62-9", nombre: "Mauro", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "b62-10", nombre: "Zózimo", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "b62-11", nombre: "Gilmar", posicion: "GOL", fuerza: 89, perfil: "portero" },
    ],
  },
  {
    id: "hol-1978",
    seleccion: "Holanda",
    seleccionSlug: "holanda",
    year: 1978,
    torneo: "Copa del Mundo",
    bandera: "🇳🇱",
    jugadores: [
      { id: "h78-1", nombre: "Rensenbrink", posicion: "PI", fuerza: 89, perfil: "extremo" },
      { id: "h78-2", nombre: "Rep", posicion: "PD", fuerza: 88, perfil: "extremo" },
      { id: "h78-3", nombre: "Neeskens", posicion: "MCD", fuerza: 90, perfil: "volante" },
      { id: "h78-4", nombre: "Haan", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "h78-5", nombre: "W. van de Kerkhof", posicion: "MEI", fuerza: 84, perfil: "volante" },
      { id: "h78-6", nombre: "R. van de Kerkhof", posicion: "EXT", fuerza: 85, perfil: "extremo" },
      { id: "h78-7", nombre: "Krol", posicion: "ZAG", fuerza: 89, perfil: "libero" },
      { id: "h78-8", nombre: "Brandts", posicion: "ZAG", fuerza: 84, perfil: "central" },
      { id: "h78-9", nombre: "Poortvliet", posicion: "LD", fuerza: 83, perfil: "lateral" },
      { id: "h78-10", nombre: "Jansen", posicion: "LE", fuerza: 85, perfil: "lateral" },
      { id: "h78-11", nombre: "Schrijvers", posicion: "GOL", fuerza: 83, perfil: "portero" },
    ],
  },
  {
    id: "bra-1982",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 1982,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b82-1", nombre: "Zico", posicion: "MEI", fuerza: 95, perfil: "playmaker" },
      { id: "b82-2", nombre: "Sócrates", posicion: "MEI", fuerza: 93, perfil: "playmaker" },
      { id: "b82-3", nombre: "Falcão", posicion: "VOL", fuerza: 90, perfil: "volante" },
      { id: "b82-4", nombre: "Cerezo", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "b82-5", nombre: "Éder", posicion: "PI", fuerza: 88, perfil: "extremo" },
      { id: "b82-6", nombre: "Serginho", posicion: "CA", fuerza: 83, perfil: "goleador" },
      { id: "b82-7", nombre: "Júnior", posicion: "LE", fuerza: 89, perfil: "lateral-ofensivo" },
      { id: "b82-8", nombre: "Leandro", posicion: "LD", fuerza: 88, perfil: "lateral-ofensivo" },
      { id: "b82-9", nombre: "Oscar", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "b82-10", nombre: "Luizinho", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "b82-11", nombre: "Waldir Peres", posicion: "GOL", fuerza: 82, perfil: "portero" },
    ],
  },
  {
    id: "fra-1986",
    seleccion: "Francia",
    seleccionSlug: "francia",
    year: 1986,
    torneo: "Copa del Mundo",
    bandera: "🇫🇷",
    jugadores: [
      { id: "f86-1", nombre: "Platini", posicion: "MEI", fuerza: 95, perfil: "playmaker" },
      { id: "f86-2", nombre: "Giresse", posicion: "MEI", fuerza: 90, perfil: "playmaker" },
      { id: "f86-3", nombre: "Tigana", posicion: "VOL", fuerza: 89, perfil: "volante" },
      { id: "f86-4", nombre: "Fernández", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "f86-5", nombre: "Stopyra", posicion: "CA", fuerza: 86, perfil: "goleador" },
      { id: "f86-6", nombre: "Rocheteau", posicion: "PD", fuerza: 86, perfil: "extremo" },
      { id: "f86-7", nombre: "Amoros", posicion: "LD", fuerza: 87, perfil: "lateral" },
      { id: "f86-8", nombre: "Battiston", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "f86-9", nombre: "Bossis", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "f86-10", nombre: "Ayache", posicion: "LE", fuerza: 83, perfil: "lateral" },
      { id: "f86-11", nombre: "Bats", posicion: "GOL", fuerza: 85, perfil: "portero" },
    ],
  },
  {
    id: "ita-1994",
    seleccion: "Italia",
    seleccionSlug: "italia",
    year: 1994,
    torneo: "Copa del Mundo",
    bandera: "🇮🇹",
    jugadores: [
      { id: "i94-1", nombre: "R. Baggio", posicion: "MEI", fuerza: 94, perfil: "playmaker" },
      { id: "i94-2", nombre: "Signori", posicion: "CA", fuerza: 87, perfil: "goleador" },
      { id: "i94-3", nombre: "Massaro", posicion: "CA", fuerza: 84, perfil: "goleador" },
      { id: "i94-4", nombre: "D. Baggio", posicion: "MCD", fuerza: 86, perfil: "volante" },
      { id: "i94-5", nombre: "Albertini", posicion: "VOL", fuerza: 87, perfil: "volante" },
      { id: "i94-6", nombre: "Donadoni", posicion: "EXT", fuerza: 88, perfil: "extremo" },
      { id: "i94-7", nombre: "Baresi", posicion: "ZAG", fuerza: 92, perfil: "libero" },
      { id: "i94-8", nombre: "Costacurta", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "i94-9", nombre: "Maldini", posicion: "LE", fuerza: 91, perfil: "lateral" },
      { id: "i94-10", nombre: "Mussi", posicion: "LD", fuerza: 84, perfil: "lateral" },
      { id: "i94-11", nombre: "Pagliuca", posicion: "GOL", fuerza: 86, perfil: "portero" },
    ],
  },
  {
    id: "bra-1998",
    seleccion: "Brasil",
    seleccionSlug: "brasil",
    year: 1998,
    torneo: "Copa del Mundo",
    bandera: "🇧🇷",
    jugadores: [
      { id: "b98-1", nombre: "Ronaldo", posicion: "CA", fuerza: 95, perfil: "goleador" },
      { id: "b98-2", nombre: "Rivaldo", posicion: "PI", fuerza: 92, perfil: "extremo" },
      { id: "b98-3", nombre: "Bebeto", posicion: "CA", fuerza: 87, perfil: "goleador" },
      { id: "b98-4", nombre: "Leonardo", posicion: "MEI", fuerza: 87, perfil: "playmaker" },
      { id: "b98-5", nombre: "Dunga", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "b98-6", nombre: "César Sampaio", posicion: "VOL", fuerza: 84, perfil: "volante" },
      { id: "b98-7", nombre: "Cafu", posicion: "LD", fuerza: 89, perfil: "lateral-ofensivo" },
      { id: "b98-8", nombre: "Roberto Carlos", posicion: "LE", fuerza: 91, perfil: "lateral-ofensivo" },
      { id: "b98-9", nombre: "Aldair", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "b98-10", nombre: "Júnior Baiano", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "b98-11", nombre: "Taffarel", posicion: "GOL", fuerza: 87, perfil: "portero" },
    ],
  },
  {
    id: "ale-2006",
    seleccion: "Alemania",
    seleccionSlug: "alemania",
    year: 2006,
    torneo: "Copa del Mundo",
    bandera: "🇩🇪",
    jugadores: [
      { id: "de06-1", nombre: "Ballack", posicion: "VOL", fuerza: 91, perfil: "playmaker" },
      { id: "de06-2", nombre: "Klose", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "de06-3", nombre: "Podolski", posicion: "CA", fuerza: 86, perfil: "goleador" },
      { id: "de06-4", nombre: "Schweinsteiger", posicion: "MEI", fuerza: 86, perfil: "volante" },
      { id: "de06-5", nombre: "Frings", posicion: "MCD", fuerza: 86, perfil: "volante" },
      { id: "de06-6", nombre: "Schneider", posicion: "EXT", fuerza: 84, perfil: "extremo" },
      { id: "de06-7", nombre: "Lahm", posicion: "LE", fuerza: 88, perfil: "lateral-ofensivo" },
      { id: "de06-8", nombre: "Friedrich", posicion: "LD", fuerza: 84, perfil: "lateral" },
      { id: "de06-9", nombre: "Mertesacker", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "de06-10", nombre: "Metzelder", posicion: "ZAG", fuerza: 84, perfil: "central" },
      { id: "de06-11", nombre: "Lehmann", posicion: "GOL", fuerza: 86, perfil: "portero" },
    ],
  },
  {
    id: "fra-2006",
    seleccion: "Francia",
    seleccionSlug: "francia",
    year: 2006,
    torneo: "Copa del Mundo",
    bandera: "🇫🇷",
    jugadores: [
      { id: "fr06-1", nombre: "Zidane", posicion: "MEI", fuerza: 95, perfil: "playmaker" },
      { id: "fr06-2", nombre: "Henry", posicion: "CA", fuerza: 92, perfil: "goleador" },
      { id: "fr06-3", nombre: "Ribéry", posicion: "PD", fuerza: 86, perfil: "extremo" },
      { id: "fr06-4", nombre: "Vieira", posicion: "VOL", fuerza: 89, perfil: "volante" },
      { id: "fr06-5", nombre: "Makélélé", posicion: "MCD", fuerza: 88, perfil: "volante" },
      { id: "fr06-6", nombre: "Malouda", posicion: "EXT", fuerza: 85, perfil: "extremo" },
      { id: "fr06-7", nombre: "Thuram", posicion: "ZAG", fuerza: 88, perfil: "central" },
      { id: "fr06-8", nombre: "Gallas", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "fr06-9", nombre: "Sagnol", posicion: "LD", fuerza: 85, perfil: "lateral" },
      { id: "fr06-10", nombre: "Abidal", posicion: "LE", fuerza: 86, perfil: "lateral" },
      { id: "fr06-11", nombre: "Barthez", posicion: "GOL", fuerza: 85, perfil: "portero" },
    ],
  },
  {
    id: "hol-2010",
    seleccion: "Holanda",
    seleccionSlug: "holanda",
    year: 2010,
    torneo: "Copa del Mundo",
    bandera: "🇳🇱",
    jugadores: [
      { id: "h10-1", nombre: "Sneijder", posicion: "MEI", fuerza: 92, perfil: "playmaker" },
      { id: "h10-2", nombre: "Robben", posicion: "PD", fuerza: 93, perfil: "extremo" },
      { id: "h10-3", nombre: "Van Persie", posicion: "CA", fuerza: 90, perfil: "goleador" },
      { id: "h10-4", nombre: "Kuyt", posicion: "EXT", fuerza: 85, perfil: "extremo" },
      { id: "h10-5", nombre: "Van Bommel", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "h10-6", nombre: "De Jong", posicion: "VOL", fuerza: 85, perfil: "volante" },
      { id: "h10-7", nombre: "Van Bronckhorst", posicion: "LE", fuerza: 86, perfil: "lateral" },
      { id: "h10-8", nombre: "Van der Wiel", posicion: "LD", fuerza: 84, perfil: "lateral" },
      { id: "h10-9", nombre: "Heitinga", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "h10-10", nombre: "Mathijsen", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "h10-11", nombre: "Stekelenburg", posicion: "GOL", fuerza: 85, perfil: "portero" },
    ],
  },
  {
    id: "arg-2014",
    seleccion: "Argentina",
    seleccionSlug: "argentina",
    year: 2014,
    torneo: "Copa del Mundo",
    bandera: "🇦🇷",
    jugadores: [
      { id: "ar14-1", nombre: "Messi", posicion: "CA", fuerza: 96, perfil: "playmaker" },
      { id: "ar14-2", nombre: "Higuaín", posicion: "CA", fuerza: 88, perfil: "goleador" },
      { id: "ar14-3", nombre: "Di María", posicion: "PD", fuerza: 90, perfil: "extremo" },
      { id: "ar14-4", nombre: "Lavezzi", posicion: "PI", fuerza: 85, perfil: "extremo" },
      { id: "ar14-5", nombre: "Mascherano", posicion: "MCD", fuerza: 90, perfil: "volante" },
      { id: "ar14-6", nombre: "Biglia", posicion: "VOL", fuerza: 85, perfil: "volante" },
      { id: "ar14-7", nombre: "Zabaleta", posicion: "LD", fuerza: 86, perfil: "lateral" },
      { id: "ar14-8", nombre: "Rojo", posicion: "LE", fuerza: 84, perfil: "lateral" },
      { id: "ar14-9", nombre: "Garay", posicion: "ZAG", fuerza: 86, perfil: "central" },
      { id: "ar14-10", nombre: "Demichelis", posicion: "ZAG", fuerza: 84, perfil: "central" },
      { id: "ar14-11", nombre: "Romero", posicion: "GOL", fuerza: 86, perfil: "portero" },
    ],
  },
  {
    id: "cro-2018",
    seleccion: "Croacia",
    seleccionSlug: "croacia",
    year: 2018,
    torneo: "Copa del Mundo",
    bandera: "🇭🇷",
    jugadores: [
      { id: "cr18-1", nombre: "Modrić", posicion: "MEI", fuerza: 94, perfil: "playmaker" },
      { id: "cr18-2", nombre: "Rakitić", posicion: "VOL", fuerza: 89, perfil: "volante" },
      { id: "cr18-3", nombre: "Perišić", posicion: "EXT", fuerza: 88, perfil: "extremo" },
      { id: "cr18-4", nombre: "Mandžukić", posicion: "CA", fuerza: 87, perfil: "goleador" },
      { id: "cr18-5", nombre: "Rebić", posicion: "PD", fuerza: 84, perfil: "extremo" },
      { id: "cr18-6", nombre: "Brozović", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "cr18-7", nombre: "Vrsaljko", posicion: "LD", fuerza: 85, perfil: "lateral" },
      { id: "cr18-8", nombre: "Strinić", posicion: "LE", fuerza: 83, perfil: "lateral" },
      { id: "cr18-9", nombre: "Lovren", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "cr18-10", nombre: "Vida", posicion: "ZAG", fuerza: 84, perfil: "central" },
      { id: "cr18-11", nombre: "Subašić", posicion: "GOL", fuerza: 85, perfil: "portero" },
    ],
  },
  {
    id: "fra-2022",
    seleccion: "Francia",
    seleccionSlug: "francia",
    year: 2022,
    torneo: "Copa del Mundo",
    bandera: "🇫🇷",
    jugadores: [
      { id: "fr22-1", nombre: "Mbappé", posicion: "CA", fuerza: 95, perfil: "goleador" },
      { id: "fr22-2", nombre: "Griezmann", posicion: "MEI", fuerza: 91, perfil: "mediapunta" },
      { id: "fr22-3", nombre: "Giroud", posicion: "CA", fuerza: 86, perfil: "goleador" },
      { id: "fr22-4", nombre: "Dembélé", posicion: "PD", fuerza: 87, perfil: "extremo" },
      { id: "fr22-5", nombre: "Tchouaméni", posicion: "MCD", fuerza: 88, perfil: "volante" },
      { id: "fr22-6", nombre: "Rabiot", posicion: "VOL", fuerza: 85, perfil: "volante" },
      { id: "fr22-7", nombre: "T. Hernández", posicion: "LE", fuerza: 87, perfil: "lateral-ofensivo" },
      { id: "fr22-8", nombre: "Koundé", posicion: "LD", fuerza: 86, perfil: "lateral" },
      { id: "fr22-9", nombre: "Varane", posicion: "ZAG", fuerza: 87, perfil: "central" },
      { id: "fr22-10", nombre: "Upamecano", posicion: "ZAG", fuerza: 85, perfil: "central" },
      { id: "fr22-11", nombre: "Lloris", posicion: "GOL", fuerza: 87, perfil: "portero" },
    ],
  },
  {
    id: "mar-2022",
    seleccion: "Marruecos",
    seleccionSlug: "marruecos",
    year: 2022,
    torneo: "Copa del Mundo",
    bandera: "🇲🇦",
    jugadores: [
      { id: "ma22-1", nombre: "Hakimi", posicion: "LD", fuerza: 88, perfil: "lateral-ofensivo" },
      { id: "ma22-2", nombre: "Ziyech", posicion: "PD", fuerza: 87, perfil: "extremo" },
      { id: "ma22-3", nombre: "En-Nesyri", posicion: "CA", fuerza: 84, perfil: "goleador" },
      { id: "ma22-4", nombre: "Amrabat", posicion: "MCD", fuerza: 87, perfil: "volante" },
      { id: "ma22-5", nombre: "Ounahi", posicion: "VOL", fuerza: 84, perfil: "volante" },
      { id: "ma22-6", nombre: "Boufal", posicion: "MEI", fuerza: 83, perfil: "extremo" },
      { id: "ma22-7", nombre: "Mazraoui", posicion: "LE", fuerza: 84, perfil: "lateral" },
      { id: "ma22-8", nombre: "Saïss", posicion: "ZAG", fuerza: 84, perfil: "central" },
      { id: "ma22-9", nombre: "Aguerd", posicion: "ZAG", fuerza: 83, perfil: "central" },
      { id: "ma22-10", nombre: "Hamdallah", posicion: "CA", fuerza: 82, perfil: "goleador" },
      { id: "ma22-11", nombre: "Bono", posicion: "GOL", fuerza: 86, perfil: "portero" },
    ],
  },
];

// Los accessors reciben el POOL a usar (Draft de Ligas → plantillas de clubes de
// la liga del usuario; por defecto, las selecciones históricas). Así el mismo
// motor sirve para ambos. `base` acota el pool y siempre hay fallback no vacío.
export function getPlantillaAleatoria(base: DraftPlantilla[] = PLANTILLAS, excluirId?: string): DraftPlantilla {
  const src = base.length > 0 ? base : PLANTILLAS;
  const pool = excluirId ? src.filter((p) => p.id !== excluirId) : src;
  const from = pool.length > 0 ? pool : src;
  return from[Math.floor(Math.random() * from.length)];
}

// "Otro equipo": otro del MISMO año/época, distinto club. Si no hay, cualquier otro.
export function getOtraSeleccion(actual: DraftPlantilla, base: DraftPlantilla[] = PLANTILLAS): DraftPlantilla {
  const src = base.length > 0 ? base : PLANTILLAS;
  const mismoAnio = src.filter((p) => p.year === actual.year && p.seleccionSlug !== actual.seleccionSlug);
  const pool = mismoAnio.length > 0 ? mismoAnio : src.filter((p) => p.id !== actual.id);
  const from = pool.length > 0 ? pool : src;
  return from[Math.floor(Math.random() * from.length)];
}

// "Otra época": una plantilla de otro año.
export function getOtroMundial(actual: DraftPlantilla, base: DraftPlantilla[] = PLANTILLAS): DraftPlantilla {
  const src = base.length > 0 ? base : PLANTILLAS;
  const otrosAnios = src.filter((p) => p.year !== actual.year);
  const pool = otrosAnios.length > 0 ? otrosAnios : src.filter((p) => p.id !== actual.id);
  const from = pool.length > 0 ? pool : src;
  return from[Math.floor(Math.random() * from.length)];
}
