// src/lib/draft/plantillas-ligas.ts
//
// Plantillas de CLUBES icónicos por liga para el "Draft de Ligas" (pivote del
// antiguo Draft Mundial de selecciones). Mismo formato que las selecciones
// históricas (11 jugadores con posición + fuerza), pero etiquetadas con `liga`
// para sesgar el draft a la(s) liga(s) que sigue el usuario.
//
// Datos curados (XI icónicos reales), evergreen, sin dependencia de api-football.

import { DraftPlantilla } from "./types";
import { PLANTILLAS } from "./plantillas";
import { getCompetition } from "@/data/competitions";

export const CLUB_PLANTILLAS: DraftPlantilla[] = [
  {"id":"ldu-quito-2008","seleccion":"LDU de Quito","seleccionSlug":"ldu-quito","year":2008,"torneo":"Campeón Copa Libertadores 2008","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"ldu08-1","nombre":"José Francisco Cevallos","posicion":"GOL","fuerza":87,"perfil":"portero"},{"id":"ldu08-2","nombre":"Neicer Reasco","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"ldu08-3","nombre":"Norberto Araujo","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"ldu08-4","nombre":"Jorge Guagua","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"ldu08-5","nombre":"Paúl Ambrosi","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"ldu08-6","nombre":"Patricio Urrutia","posicion":"MCD","fuerza":83,"perfil":"volante"},{"id":"ldu08-7","nombre":"William Araujo","posicion":"VOL","fuerza":77,"perfil":"volante"},{"id":"ldu08-8","nombre":"Enrique Vera","posicion":"MEI","fuerza":82,"perfil":"mediapunta"},{"id":"ldu08-9","nombre":"Joffre Guerrón","posicion":"PD","fuerza":84,"perfil":"extremo"},{"id":"ldu08-10","nombre":"Luis Bolaños","posicion":"PI","fuerza":81,"perfil":"extremo"},{"id":"ldu08-11","nombre":"Claudio Bieler","posicion":"CA","fuerza":89,"perfil":"goleador"}]},
  {"id":"barcelona-sc-2017","seleccion":"Barcelona SC","seleccionSlug":"barcelona-sc","year":2017,"torneo":"Generación dorada 2016-2021 (semifinalista Libertadores 2017)","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"bsc-1","nombre":"Máximo Banguera","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"bsc-2","nombre":"Antonio Valencia","posicion":"LD","fuerza":86,"perfil":"lateral-ofensivo"},{"id":"bsc-3","nombre":"Gabriel Marques","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"bsc-4","nombre":"Darío Aimar","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"bsc-5","nombre":"Mario Pineida","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"bsc-6","nombre":"Matías Oyola","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"bsc-7","nombre":"Fernando Gaibor","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"bsc-8","nombre":"Damián Díaz","posicion":"MEI","fuerza":89,"perfil":"playmaker"},{"id":"bsc-9","nombre":"Michael Arroyo","posicion":"PD","fuerza":82,"perfil":"extremo"},{"id":"bsc-10","nombre":"Fidel Martínez","posicion":"PI","fuerza":80,"perfil":"extremo"},{"id":"bsc-11","nombre":"Jonatan Álvez","posicion":"CA","fuerza":81,"perfil":"goleador"}]},
  {"id":"emelec-2015","seleccion":"Emelec","seleccionSlug":"emelec","year":2015,"torneo":"Tricampeón Serie A 2013-2015 (era dorada)","bandera":"🇪🇨","liga":"ligapro-ecuador","jugadores":[{"id":"eme-1","nombre":"Esteban Dreer","posicion":"GOL","fuerza":83,"perfil":"portero"},{"id":"eme-2","nombre":"Romario Caicedo","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"eme-3","nombre":"Gabriel Achilier","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"eme-4","nombre":"Frickson Erazo","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"eme-5","nombre":"Óscar Bagüí","posicion":"LE","fuerza":78,"perfil":"lateral"},{"id":"eme-6","nombre":"Pedro Quiñónez","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"eme-7","nombre":"Junior Sornoza","posicion":"VOL","fuerza":83,"perfil":"playmaker"},{"id":"eme-8","nombre":"Marcos Mondaini","posicion":"MEI","fuerza":81,"perfil":"mediapunta"},{"id":"eme-9","nombre":"Ángel Mena","posicion":"PD","fuerza":85,"perfil":"extremo"},{"id":"eme-10","nombre":"Enner Valencia","posicion":"CA","fuerza":88,"perfil":"goleador"},{"id":"eme-11","nombre":"Miller Bolaños","posicion":"PI","fuerza":83,"perfil":"segundo-delantero"}]},
  {"id":"america-2013","seleccion":"Club América","seleccionSlug":"america","year":2013,"torneo":"Campeón Clausura 2013","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"ame13-1","nombre":"Moisés Muñoz","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"ame13-2","nombre":"Paul Aguilar","posicion":"LD","fuerza":85,"perfil":"lateral-ofensivo"},{"id":"ame13-3","nombre":"Aquivaldo Mosquera","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"ame13-4","nombre":"Juan Carlos Valenzuela","posicion":"ZAG","fuerza":75,"perfil":"central"},{"id":"ame13-5","nombre":"Miguel Layún","posicion":"LE","fuerza":84,"perfil":"lateral-ofensivo"},{"id":"ame13-6","nombre":"Jesús Molina","posicion":"MCD","fuerza":79,"perfil":"volante"},{"id":"ame13-7","nombre":"Osvaldo Martínez","posicion":"VOL","fuerza":81,"perfil":"volante"},{"id":"ame13-8","nombre":"Rubens Sambueza","posicion":"MEI","fuerza":86,"perfil":"playmaker"},{"id":"ame13-9","nombre":"Raúl Jiménez","posicion":"PD","fuerza":83,"perfil":"goleador"},{"id":"ame13-10","nombre":"Christian Benítez","posicion":"CA","fuerza":89,"perfil":"goleador"},{"id":"ame13-11","nombre":"Luis Gabriel Rey","posicion":"PI","fuerza":74,"perfil":"extremo"}]},
  {"id":"chivas-2017","seleccion":"Chivas de Guadalajara","seleccionSlug":"chivas","year":2017,"torneo":"Campeón Clausura 2017","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"chi17-1","nombre":"Rodolfo Cota","posicion":"GOL","fuerza":81,"perfil":"portero"},{"id":"chi17-2","nombre":"Jesús Sánchez","posicion":"LD","fuerza":76,"perfil":"lateral"},{"id":"chi17-3","nombre":"Oswaldo Alanís","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"chi17-4","nombre":"Jair Pereira","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"chi17-5","nombre":"Carlos Salcido","posicion":"LE","fuerza":80,"perfil":"lateral"},{"id":"chi17-6","nombre":"José Juan Vázquez","posicion":"MCD","fuerza":79,"perfil":"volante"},{"id":"chi17-7","nombre":"Orbelín Pineda","posicion":"VOL","fuerza":85,"perfil":"volante"},{"id":"chi17-8","nombre":"Rodolfo Pizarro","posicion":"MEI","fuerza":87,"perfil":"mediapunta"},{"id":"chi17-9","nombre":"Isaác Brizuela","posicion":"PD","fuerza":82,"perfil":"extremo"},{"id":"chi17-10","nombre":"Alan Pulido","posicion":"CA","fuerza":86,"perfil":"goleador"},{"id":"chi17-11","nombre":"Chofis López","posicion":"PI","fuerza":80,"perfil":"extremo"}]},
  {"id":"cruz-azul-2021","seleccion":"Cruz Azul","seleccionSlug":"cruz-azul","year":2021,"torneo":"Campeón Guardianes 2021","bandera":"🇲🇽","liga":"liga-mx","jugadores":[{"id":"cru21-1","nombre":"Jesús Corona","posicion":"GOL","fuerza":83,"perfil":"portero"},{"id":"cru21-2","nombre":"Juan Escobedo","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"cru21-3","nombre":"Pablo Aguilar","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"cru21-4","nombre":"Julio César Domínguez","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"cru21-5","nombre":"Adrián Aldrete","posicion":"LE","fuerza":77,"perfil":"lateral"},{"id":"cru21-6","nombre":"Luis Romo","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"cru21-7","nombre":"Rafael Baca","posicion":"VOL","fuerza":78,"perfil":"volante"},{"id":"cru21-8","nombre":"Yoshimar Yotún","posicion":"MEI","fuerza":83,"perfil":"playmaker"},{"id":"cru21-9","nombre":"Roberto Alvarado","posicion":"PD","fuerza":83,"perfil":"extremo"},{"id":"cru21-10","nombre":"Jonathan Rodríguez","posicion":"CA","fuerza":88,"perfil":"goleador"},{"id":"cru21-11","nombre":"Elías Hernández","posicion":"PI","fuerza":79,"perfil":"extremo"}]},
  {"id":"barcelona-2011","seleccion":"FC Barcelona","seleccionSlug":"barcelona","year":2011,"torneo":"Champions League 2011 (Pep / Messi)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"bar11-1","nombre":"Víctor Valdés","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"bar11-2","nombre":"Dani Alves","posicion":"LD","fuerza":88,"perfil":"lateral-ofensivo"},{"id":"bar11-3","nombre":"Gerard Piqué","posicion":"ZAG","fuerza":87,"perfil":"central"},{"id":"bar11-4","nombre":"Javier Mascherano","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"bar11-5","nombre":"Éric Abidal","posicion":"LE","fuerza":83,"perfil":"lateral"},{"id":"bar11-6","nombre":"Sergio Busquets","posicion":"MCD","fuerza":87,"perfil":"volante"},{"id":"bar11-7","nombre":"Xavi Hernández","posicion":"VOL","fuerza":92,"perfil":"playmaker"},{"id":"bar11-8","nombre":"Andrés Iniesta","posicion":"MEI","fuerza":92,"perfil":"mediapunta"},{"id":"bar11-9","nombre":"Pedro Rodríguez","posicion":"PD","fuerza":84,"perfil":"extremo"},{"id":"bar11-10","nombre":"Lionel Messi","posicion":"CA","fuerza":97,"perfil":"goleador"},{"id":"bar11-11","nombre":"David Villa","posicion":"PI","fuerza":89,"perfil":"segundo-delantero"}]},
  {"id":"realmadrid-2017","seleccion":"Real Madrid","seleccionSlug":"real-madrid","year":2017,"torneo":"Champions League 2017 (BBC / La Duodécima)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"rma17-1","nombre":"Keylor Navas","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"rma17-2","nombre":"Dani Carvajal","posicion":"LD","fuerza":84,"perfil":"lateral-ofensivo"},{"id":"rma17-3","nombre":"Sergio Ramos","posicion":"ZAG","fuerza":90,"perfil":"central"},{"id":"rma17-4","nombre":"Raphaël Varane","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"rma17-5","nombre":"Marcelo","posicion":"LE","fuerza":87,"perfil":"lateral-ofensivo"},{"id":"rma17-6","nombre":"Casemiro","posicion":"MCD","fuerza":86,"perfil":"volante"},{"id":"rma17-7","nombre":"Toni Kroos","posicion":"VOL","fuerza":89,"perfil":"playmaker"},{"id":"rma17-8","nombre":"Luka Modrić","posicion":"MEI","fuerza":89,"perfil":"mediapunta"},{"id":"rma17-9","nombre":"Gareth Bale","posicion":"PD","fuerza":89,"perfil":"extremo"},{"id":"rma17-10","nombre":"Karim Benzema","posicion":"CA","fuerza":87,"perfil":"segundo-delantero"},{"id":"rma17-11","nombre":"Cristiano Ronaldo","posicion":"PI","fuerza":96,"perfil":"goleador"}]},
  {"id":"atletico-2014","seleccion":"Atlético de Madrid","seleccionSlug":"atletico-madrid","year":2014,"torneo":"LaLiga 2013-14 (Simeone, campeones)","bandera":"🇪🇸","liga":"laliga","jugadores":[{"id":"atm14-1","nombre":"Thibaut Courtois","posicion":"GOL","fuerza":88,"perfil":"portero"},{"id":"atm14-2","nombre":"Juanfran","posicion":"LD","fuerza":80,"perfil":"lateral"},{"id":"atm14-3","nombre":"Diego Godín","posicion":"ZAG","fuerza":87,"perfil":"central"},{"id":"atm14-4","nombre":"Miranda","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"atm14-5","nombre":"Filipe Luís","posicion":"LE","fuerza":83,"perfil":"lateral-ofensivo"},{"id":"atm14-6","nombre":"Gabi","posicion":"MCD","fuerza":82,"perfil":"volante"},{"id":"atm14-7","nombre":"Tiago Mendes","posicion":"VOL","fuerza":80,"perfil":"volante"},{"id":"atm14-8","nombre":"Koke","posicion":"MEI","fuerza":84,"perfil":"playmaker"},{"id":"atm14-9","nombre":"Arda Turan","posicion":"PD","fuerza":84,"perfil":"extremo"},{"id":"atm14-10","nombre":"Diego Costa","posicion":"CA","fuerza":90,"perfil":"goleador"},{"id":"atm14-11","nombre":"Cristian Rodríguez","posicion":"PI","fuerza":78,"perfil":"extremo"}]},
  {"id":"boca-juniors-2000","seleccion":"Boca Juniors","seleccionSlug":"boca-juniors","year":2000,"torneo":"Copa Libertadores 2000 + Intercontinental (vs Real Madrid)","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"boc00-1","nombre":"Córdoba","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"boc00-2","nombre":"Ibarra","posicion":"LD","fuerza":82,"perfil":"lateral"},{"id":"boc00-3","nombre":"Walter Samuel","posicion":"ZAG","fuerza":89,"perfil":"central"},{"id":"boc00-4","nombre":"Bermúdez","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"boc00-5","nombre":"Matellán","posicion":"LE","fuerza":75,"perfil":"lateral"},{"id":"boc00-6","nombre":"Battaglia","posicion":"MCD","fuerza":83,"perfil":"volante"},{"id":"boc00-7","nombre":"Serna","posicion":"VOL","fuerza":81,"perfil":"volante"},{"id":"boc00-8","nombre":"Riquelme","posicion":"MEI","fuerza":96,"perfil":"playmaker"},{"id":"boc00-9","nombre":"Guillermo Barros Schelotto","posicion":"PD","fuerza":86,"perfil":"mediapunta"},{"id":"boc00-10","nombre":"Palermo","posicion":"CA","fuerza":90,"perfil":"goleador"},{"id":"boc00-11","nombre":"Marcelo Delgado","posicion":"PI","fuerza":83,"perfil":"segundo-delantero"}]},
  {"id":"river-plate-2018","seleccion":"River Plate","seleccionSlug":"river-plate","year":2018,"torneo":"Copa Libertadores 2018 (final vs Boca en Madrid)","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"riv18-1","nombre":"Armani","posicion":"GOL","fuerza":87,"perfil":"portero"},{"id":"riv18-2","nombre":"Montiel","posicion":"LD","fuerza":80,"perfil":"lateral-ofensivo"},{"id":"riv18-3","nombre":"Pinola","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"riv18-4","nombre":"Maidana","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"riv18-5","nombre":"Casco","posicion":"LE","fuerza":78,"perfil":"lateral"},{"id":"riv18-6","nombre":"Ponzio","posicion":"MCD","fuerza":82,"perfil":"volante"},{"id":"riv18-7","nombre":"Enzo Pérez","posicion":"VOL","fuerza":85,"perfil":"volante"},{"id":"riv18-8","nombre":"Ignacio Fernández","posicion":"MEI","fuerza":85,"perfil":"mediapunta"},{"id":"riv18-9","nombre":"Gonzalo Martínez","posicion":"PD","fuerza":88,"perfil":"extremo"},{"id":"riv18-10","nombre":"Pratto","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"riv18-11","nombre":"Quintero","posicion":"PI","fuerza":89,"perfil":"playmaker"}]},
  {"id":"independiente-1973","seleccion":"Independiente","seleccionSlug":"independiente","year":1973,"torneo":"Libertadores 1973 e Intercontinental vs Juventus (Rey de Copas)","bandera":"🇦🇷","liga":"liga-argentina","jugadores":[{"id":"ind73-1","nombre":"Santoro","posicion":"GOL","fuerza":85,"perfil":"portero"},{"id":"ind73-2","nombre":"Commisso","posicion":"LD","fuerza":75,"perfil":"lateral"},{"id":"ind73-3","nombre":"Francisco Sá","posicion":"ZAG","fuerza":84,"perfil":"libero"},{"id":"ind73-4","nombre":"Rogel","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"ind73-5","nombre":"Pavoni","posicion":"LE","fuerza":82,"perfil":"lateral-ofensivo"},{"id":"ind73-6","nombre":"Pastoriza","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"ind73-7","nombre":"Galván","posicion":"VOL","fuerza":79,"perfil":"volante"},{"id":"ind73-8","nombre":"Bochini","posicion":"MEI","fuerza":92,"perfil":"playmaker"},{"id":"ind73-9","nombre":"Balbuena","posicion":"PD","fuerza":82,"perfil":"extremo"},{"id":"ind73-10","nombre":"Bertoni","posicion":"CA","fuerza":86,"perfil":"goleador"},{"id":"ind73-11","nombre":"Raimondo","posicion":"PI","fuerza":78,"perfil":"segundo-delantero"}]},
  {"id":"santos-1962","seleccion":"Santos FC","seleccionSlug":"santos","year":1962,"torneo":"Copa Libertadores e Intercontinental 1962","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"san62-1","nombre":"Gylmar","posicion":"GOL","fuerza":86,"perfil":"portero"},{"id":"san62-2","nombre":"Lima","posicion":"LD","fuerza":78,"perfil":"lateral"},{"id":"san62-3","nombre":"Mauro Ramos","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"san62-4","nombre":"Calvet","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"san62-5","nombre":"Dalmo","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"san62-6","nombre":"Zito","posicion":"MCD","fuerza":85,"perfil":"volante"},{"id":"san62-7","nombre":"Mengálvio","posicion":"MEI","fuerza":82,"perfil":"playmaker"},{"id":"san62-8","nombre":"Dorval","posicion":"PD","fuerza":80,"perfil":"extremo"},{"id":"san62-9","nombre":"Coutinho","posicion":"CA","fuerza":87,"perfil":"goleador"},{"id":"san62-10","nombre":"Pelé","posicion":"MEI","fuerza":97,"perfil":"mediapunta"},{"id":"san62-11","nombre":"Pepe","posicion":"PI","fuerza":85,"perfil":"extremo"}]},
  {"id":"flamengo-1981","seleccion":"CR Flamengo","seleccionSlug":"flamengo","year":1981,"torneo":"Libertadores e Intercontinental 1981","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"fla81-1","nombre":"Raul","posicion":"GOL","fuerza":80,"perfil":"portero"},{"id":"fla81-2","nombre":"Leandro","posicion":"LD","fuerza":87,"perfil":"lateral-ofensivo"},{"id":"fla81-3","nombre":"Marinho","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"fla81-4","nombre":"Mozer","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"fla81-5","nombre":"Júnior","posicion":"LE","fuerza":88,"perfil":"lateral-ofensivo"},{"id":"fla81-6","nombre":"Andrade","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"fla81-7","nombre":"Adílio","posicion":"VOL","fuerza":78,"perfil":"volante"},{"id":"fla81-8","nombre":"Zico","posicion":"MEI","fuerza":95,"perfil":"playmaker"},{"id":"fla81-9","nombre":"Tita","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"fla81-10","nombre":"Nunes","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"fla81-11","nombre":"Lico","posicion":"PI","fuerza":76,"perfil":"extremo"}]},
  {"id":"sao-paulo-1992","seleccion":"São Paulo FC","seleccionSlug":"sao-paulo","year":1992,"torneo":"Libertadores e Intercontinental 1992-93 (Telê)","bandera":"🇧🇷","liga":"brasileirao","jugadores":[{"id":"spfc92-1","nombre":"Zetti","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"spfc92-2","nombre":"Cafú","posicion":"LD","fuerza":88,"perfil":"lateral-ofensivo"},{"id":"spfc92-3","nombre":"Ronaldão","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"spfc92-4","nombre":"Válber","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"spfc92-5","nombre":"Ronaldo Luiz","posicion":"LE","fuerza":75,"perfil":"lateral"},{"id":"spfc92-6","nombre":"Pintado","posicion":"MCD","fuerza":77,"perfil":"volante"},{"id":"spfc92-7","nombre":"Raí","posicion":"MEI","fuerza":90,"perfil":"playmaker"},{"id":"spfc92-8","nombre":"Müller","posicion":"MEI","fuerza":84,"perfil":"mediapunta"},{"id":"spfc92-9","nombre":"Palhinha","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"spfc92-10","nombre":"Macedo","posicion":"PD","fuerza":78,"perfil":"extremo"},{"id":"spfc92-11","nombre":"Dinho","posicion":"VOL","fuerza":75,"perfil":"volante"}]},
  {"id":"manchester-united-1999","seleccion":"Manchester United","seleccionSlug":"manchester-united","year":1999,"torneo":"El Triplete 1999 (Premier, FA Cup y Champions)","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"mun99-1","nombre":"Schmeichel","posicion":"GOL","fuerza":89,"perfil":"portero"},{"id":"mun99-2","nombre":"Gary Neville","posicion":"LD","fuerza":81,"perfil":"lateral"},{"id":"mun99-3","nombre":"Jaap Stam","posicion":"ZAG","fuerza":87,"perfil":"central"},{"id":"mun99-4","nombre":"Ronny Johnsen","posicion":"ZAG","fuerza":77,"perfil":"central"},{"id":"mun99-5","nombre":"Denis Irwin","posicion":"LE","fuerza":82,"perfil":"lateral"},{"id":"mun99-6","nombre":"Beckham","posicion":"EXT","fuerza":89,"perfil":"extremo"},{"id":"mun99-7","nombre":"Roy Keane","posicion":"MCD","fuerza":90,"perfil":"volante"},{"id":"mun99-8","nombre":"Scholes","posicion":"MEI","fuerza":88,"perfil":"playmaker"},{"id":"mun99-9","nombre":"Ryan Giggs","posicion":"EXT","fuerza":89,"perfil":"extremo"},{"id":"mun99-10","nombre":"Dwight Yorke","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"mun99-11","nombre":"Andy Cole","posicion":"CA","fuerza":84,"perfil":"goleador"}]},
  {"id":"liverpool-2020","seleccion":"Liverpool FC","seleccionSlug":"liverpool","year":2020,"torneo":"Premier League 2019-20","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"liv20-1","nombre":"Alisson","posicion":"GOL","fuerza":89,"perfil":"portero"},{"id":"liv20-2","nombre":"Alexander-Arnold","posicion":"LD","fuerza":86,"perfil":"lateral-ofensivo"},{"id":"liv20-3","nombre":"Van Dijk","posicion":"ZAG","fuerza":91,"perfil":"central"},{"id":"liv20-4","nombre":"Matip","posicion":"ZAG","fuerza":81,"perfil":"central"},{"id":"liv20-5","nombre":"Robertson","posicion":"LE","fuerza":86,"perfil":"lateral-ofensivo"},{"id":"liv20-6","nombre":"Fabinho","posicion":"MCD","fuerza":85,"perfil":"volante"},{"id":"liv20-7","nombre":"Henderson","posicion":"VOL","fuerza":84,"perfil":"volante"},{"id":"liv20-8","nombre":"Wijnaldum","posicion":"MEI","fuerza":83,"perfil":"volante"},{"id":"liv20-9","nombre":"Salah","posicion":"PD","fuerza":90,"perfil":"extremo"},{"id":"liv20-10","nombre":"Firmino","posicion":"CA","fuerza":85,"perfil":"segundo-delantero"},{"id":"liv20-11","nombre":"Mané","posicion":"PI","fuerza":89,"perfil":"extremo"}]},
  {"id":"arsenal-2004","seleccion":"Arsenal FC","seleccionSlug":"arsenal","year":2004,"torneo":"Los Invencibles 2003-04 (Premier invicto)","bandera":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","liga":"premier-league","jugadores":[{"id":"ars04-1","nombre":"Lehmann","posicion":"GOL","fuerza":83,"perfil":"portero"},{"id":"ars04-2","nombre":"Lauren","posicion":"LD","fuerza":79,"perfil":"lateral"},{"id":"ars04-3","nombre":"Sol Campbell","posicion":"ZAG","fuerza":86,"perfil":"central"},{"id":"ars04-4","nombre":"Kolo Touré","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"ars04-5","nombre":"Ashley Cole","posicion":"LE","fuerza":85,"perfil":"lateral-ofensivo"},{"id":"ars04-6","nombre":"Ljungberg","posicion":"EXT","fuerza":83,"perfil":"extremo"},{"id":"ars04-7","nombre":"Vieira","posicion":"VOL","fuerza":90,"perfil":"volante"},{"id":"ars04-8","nombre":"Gilberto Silva","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"ars04-9","nombre":"Pirès","posicion":"MEI","fuerza":87,"perfil":"mediapunta"},{"id":"ars04-10","nombre":"Henry","posicion":"CA","fuerza":94,"perfil":"goleador"},{"id":"ars04-11","nombre":"Bergkamp","posicion":"CA","fuerza":89,"perfil":"segundo-delantero"}]},,
  {"id":"caracas-fc-2009","seleccion":"Caracas FC","seleccionSlug":"caracas-fc","year":2009,"torneo":"Primera División de Venezuela / Copa Libertadores","bandera":"🇻🇪","liga":"liga-futve","jugadores":[{"id":"sanhouse","nombre":"Manuel Sanhouse","posicion":"GOL","fuerza":77,"perfil":"portero"},{"id":"fuenmayor","nombre":"Juan Fuenmayor","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"jm-rey","nombre":"José Manuel Rey","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"vizcarrondo","nombre":"Oswaldo Vizcarrondo","posicion":"ZAG","fuerza":84,"perfil":"central"},{"id":"a-cichero","nombre":"Alejandro Cichero","posicion":"LE","fuerza":78,"perfil":"lateral-ofensivo"},{"id":"lucena","nombre":"Franklin Lucena","posicion":"MCD","fuerza":80,"perfil":"volante"},{"id":"seijas","nombre":"Luis Manuel Seijas","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"jorge-rojas","nombre":"Jorge Rojas","posicion":"MEI","fuerza":86,"perfil":"playmaker"},{"id":"paez","nombre":"Ricardo Páez","posicion":"PD","fuerza":81,"perfil":"extremo"},{"id":"cesar-gonzalez","nombre":"César González","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"miku","nombre":"Nicolás \"Miku\" Fedor","posicion":"PI","fuerza":82,"perfil":"segundo-delantero"}]},
  {"id":"deportivo-tachira-2010","seleccion":"Deportivo Táchira","seleccionSlug":"deportivo-tachira","year":2010,"torneo":"Primera División de Venezuela / Copa Libertadores (era dorada)","bandera":"🇻🇪","liga":"liga-futve","jugadores":[{"id":"romo","nombre":"Rafael Romo","posicion":"GOL","fuerza":79,"perfil":"portero"},{"id":"cumana","nombre":"Yohan Cumaná","posicion":"LD","fuerza":71,"perfil":"lateral"},{"id":"perozo","nombre":"Grenddy Perozo","posicion":"ZAG","fuerza":79,"perfil":"central"},{"id":"chancellor","nombre":"John Chancellor","posicion":"ZAG","fuerza":82,"perfil":"central"},{"id":"wilker-angel","nombre":"Wilker Ángel","posicion":"LE","fuerza":74,"perfil":"central"},{"id":"anderson-contreras","nombre":"Anderson Contreras","posicion":"MCD","fuerza":77,"perfil":"volante"},{"id":"gerzon-chacon","nombre":"Gerzon Chacón","posicion":"VOL","fuerza":75,"perfil":"volante"},{"id":"urdaneta","nombre":"Gabriel Urdaneta","posicion":"MEI","fuerza":86,"perfil":"playmaker"},{"id":"torrealba","nombre":"José Luis Torrealba","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"digiorgi","nombre":"Giacomo Di Giorgi","posicion":"CA","fuerza":84,"perfil":"goleador"},{"id":"arismendi","nombre":"Daniel Arismendi","posicion":"PI","fuerza":82,"perfil":"segundo-delantero"}]},
  {"id":"zamora-fc-2013","seleccion":"Zamora FC","seleccionSlug":"zamora-fc","year":2013,"torneo":"Primera División de Venezuela / Copa Libertadores (era dorada)","bandera":"🇻🇪","liga":"liga-futve","jugadores":[{"id":"renny-vega","nombre":"Renny Vega","posicion":"GOL","fuerza":77,"perfil":"portero"},{"id":"ronald-hernandez","nombre":"Ronald Hernández","posicion":"LD","fuerza":72,"perfil":"lateral"},{"id":"jm-velasquez","nombre":"José Manuel Velásquez","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"junior-moreno","nombre":"Junior Moreno","posicion":"ZAG","fuerza":74,"perfil":"central"},{"id":"alexander-gonzalez","nombre":"Alexander González","posicion":"LE","fuerza":74,"perfil":"lateral"},{"id":"romulo-otero","nombre":"Rómulo Otero","posicion":"VOL","fuerza":80,"perfil":"playmaker"},{"id":"del-valle","nombre":"Jonathan Del Valle","posicion":"EXT","fuerza":81,"perfil":"extremo"},{"id":"alejandro-guerra","nombre":"Alejandro Guerra","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"orozco","nombre":"Yohandry Orozco","posicion":"EXT","fuerza":84,"perfil":"extremo"},{"id":"falcon","nombre":"Juan Falcón","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"gelmin-rivas","nombre":"Gelmin Rivas","posicion":"PI","fuerza":76,"perfil":"segundo-delantero"}]},
  {"id":"atletico-nacional-1989","seleccion":"Atlético Nacional","seleccionSlug":"atletico-nacional","year":1989,"torneo":"Copa Libertadores 1989 (campeón)","bandera":"🇨🇴","liga":"primera-a-colombia","jugadores":[{"id":"higuita","nombre":"René Higuita","posicion":"GOL","fuerza":89,"perfil":"portero"},{"id":"carmona","nombre":"John Jairo Carmona","posicion":"LD","fuerza":73,"perfil":"lateral"},{"id":"luis-carlos-perea","nombre":"Luis Carlos Perea","posicion":"ZAG","fuerza":80,"perfil":"central"},{"id":"andres-escobar","nombre":"Andrés Escobar","posicion":"ZAG","fuerza":85,"perfil":"central"},{"id":"gildardo-gomez","nombre":"Gildardo Gómez","posicion":"LE","fuerza":76,"perfil":"lateral"},{"id":"leonel-alvarez","nombre":"Leonel Álvarez","posicion":"MCD","fuerza":84,"perfil":"volante"},{"id":"alexis-garcia","nombre":"Alexis García","posicion":"MEI","fuerza":81,"perfil":"playmaker"},{"id":"luis-fajardo","nombre":"Luis Fajardo","posicion":"VOL","fuerza":74,"perfil":"volante"},{"id":"jaime-arango","nombre":"Jaime Arango","posicion":"EXT","fuerza":73,"perfil":"extremo"},{"id":"usuriaga","nombre":"Albeiro Usuriaga","posicion":"CA","fuerza":82,"perfil":"goleador"},{"id":"trellez","nombre":"John Jairo Tréllez","posicion":"CA","fuerza":79,"perfil":"goleador"}]},
  {"id":"millonarios-2023","seleccion":"Millonarios","seleccionSlug":"millonarios","year":2023,"torneo":"Liga BetPlay 2023-I (campeón)","bandera":"🇨🇴","liga":"primera-a-colombia","jugadores":[{"id":"montero","nombre":"Álvaro Montero","posicion":"GOL","fuerza":84,"perfil":"portero"},{"id":"perlaza","nombre":"Elvis Perlaza","posicion":"LD","fuerza":74,"perfil":"lateral"},{"id":"llinas","nombre":"Andrés Llinás","posicion":"ZAG","fuerza":78,"perfil":"central"},{"id":"jorge-arias","nombre":"Jorge Arias","posicion":"ZAG","fuerza":75,"perfil":"central"},{"id":"bertel","nombre":"Omar Bertel","posicion":"LE","fuerza":72,"perfil":"lateral"},{"id":"stiven-vega","nombre":"Stiven Vega","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"giraldo","nombre":"Daniel Giraldo","posicion":"VOL","fuerza":74,"perfil":"volante"},{"id":"catano","nombre":"Daniel Cataño","posicion":"MEI","fuerza":79,"perfil":"mediapunta"},{"id":"mackalister-silva","nombre":"David Mackalister Silva","posicion":"MEI","fuerza":85,"perfil":"playmaker"},{"id":"oscar-cortes","nombre":"Óscar Cortés","posicion":"PD","fuerza":79,"perfil":"extremo"},{"id":"leonardo-castro","nombre":"Leonardo Castro","posicion":"CA","fuerza":81,"perfil":"goleador"}]},
  {"id":"america-de-cali-1986","seleccion":"América de Cali","seleccionSlug":"america-de-cali","year":1986,"torneo":"Copa Libertadores 1986 (finalista, era dorada)","bandera":"🇨🇴","liga":"primera-a-colombia","jugadores":[{"id":"falcioni","nombre":"Julio César Falcioni","posicion":"GOL","fuerza":82,"perfil":"portero"},{"id":"hugo-valencia","nombre":"Hugo Valencia","posicion":"LD","fuerza":73,"perfil":"lateral"},{"id":"victor-espinosa","nombre":"Víctor Espinosa","posicion":"ZAG","fuerza":76,"perfil":"central"},{"id":"esterilla","nombre":"Enrique Esterilla","posicion":"ZAG","fuerza":73,"perfil":"central"},{"id":"porras","nombre":"Jorge Porras","posicion":"LE","fuerza":74,"perfil":"lateral"},{"id":"gonzalez-aquino","nombre":"Gerardo González Aquino","posicion":"MCD","fuerza":76,"perfil":"volante"},{"id":"ischia","nombre":"Carlos Ischia","posicion":"MEI","fuerza":78,"perfil":"playmaker"},{"id":"battaglia","nombre":"Juan Manuel Battaglia","posicion":"VOL","fuerza":76,"perfil":"volante"},{"id":"willington-ortiz","nombre":"Willington Ortiz","posicion":"PI","fuerza":87,"perfil":"extremo"},{"id":"cabanas","nombre":"Roberto Cabañas","posicion":"CA","fuerza":85,"perfil":"goleador"},{"id":"gareca","nombre":"Ricardo Gareca","posicion":"CA","fuerza":84,"perfil":"goleador"}]}
];

// Copas continentales → ligas DOMÉSTICAS cuyos clubes las disputan. Así, quien
// sigue "Libertadores" draftea clubes de Sudamérica; quien sigue "Champions",
// de las grandes de Europa.
const CONTINENTAL_MAP: Record<string, string[]> = {
  libertadores: ["liga-argentina", "brasileirao", "ligapro-ecuador", "primera-a-colombia", "liga-futve", "liga-mx"],
  sudamericana: ["liga-argentina", "brasileirao", "ligapro-ecuador", "primera-a-colombia", "liga-futve"],
  "champions-league": ["laliga", "premier-league", "serie-a", "bundesliga", "ligue-1", "primeira-liga"],
  "europa-league": ["laliga", "premier-league", "serie-a", "bundesliga", "ligue-1", "primeira-liga"],
  "conference-league": ["laliga", "premier-league", "serie-a", "bundesliga", "ligue-1", "primeira-liga"],
  "concacaf-champions": ["liga-mx", "mls"],
};

/**
 * Pool de plantillas de clubes para las ligas seguidas por el usuario. Expande
 * las copas continentales a sus ligas domésticas. Fallbacks encadenados para no
 * dejar NUNCA un pool vacío (el motor haría crash):
 *   1) clubes de las ligas del usuario (si hay ≥2),
 *   2) todos los clubes,
 *   3) las selecciones históricas (si aún no hay clubes cargados).
 */
export function poolForLeagues(slugs: string[]): DraftPlantilla[] {
  if (CLUB_PLANTILLAS.length === 0) return PLANTILLAS;
  if (!slugs || slugs.length === 0) return CLUB_PLANTILLAS;
  const wanted = new Set<string>();
  for (const s of slugs) {
    wanted.add(s);
    for (const d of CONTINENTAL_MAP[s] ?? []) wanted.add(d);
  }
  const filtered = CLUB_PLANTILLAS.filter((p) => p.liga && wanted.has(p.liga));
  return filtered.length >= 2 ? filtered : CLUB_PLANTILLAS;
}

/** Slugs de liga que aporta un slug (él mismo + su expansión continental). */
function expand(slug: string): Set<string> {
  return new Set<string>([slug, ...(CONTINENTAL_MAP[slug] ?? [])]);
}

/** ¿Esa liga (o copa continental) tiene al menos un club en el catálogo? */
export function leagueHasClubs(slug: string): boolean {
  const wanted = expand(slug);
  return CLUB_PLANTILLAS.some((p) => !!p.liga && wanted.has(p.liga));
}

/**
 * Pool de UNA sola liga (la elegida por el usuario en el Draft): solo clubes de
 * esa liga/copa. NUNCA mezcla otras ligas ni cae a selecciones históricas si hay
 * clubes cargados (si la liga no tuviera clubes, cae a todos los clubes, jamás al
 * Mundial). Así "elijo España → solo España".
 */
export function poolForLeague(slug: string): DraftPlantilla[] {
  if (CLUB_PLANTILLAS.length === 0) return PLANTILLAS;
  const wanted = expand(slug);
  const filtered = CLUB_PLANTILLAS.filter((p) => !!p.liga && wanted.has(p.liga));
  return filtered.length >= 2 ? filtered : CLUB_PLANTILLAS;
}

export interface DraftLeagueOption { slug: string; short: string; }

/** Ligas del catálogo que tienen clubes drafteables (para el selector). */
export const DRAFT_LEAGUES: DraftLeagueOption[] = Array.from(
  new Set(CLUB_PLANTILLAS.map((p) => p.liga).filter((s): s is string => !!s)),
).map((slug) => ({ slug, short: getCompetition(slug)?.short ?? slug }));

/**
 * Ligas ENTRE LAS QUE PUEDE ELEGIR el usuario en el Draft: las que sigue y que
 * tienen clubes (directas o vía copa continental). Si no sigue ninguna con
 * clubes, ofrecemos todas las disponibles (para que el Draft siga jugable).
 */
export function availableDraftLeagues(followed: string[]): DraftLeagueOption[] {
  const opts: DraftLeagueOption[] = [];
  const seen = new Set<string>();
  for (const slug of followed ?? []) {
    if (seen.has(slug) || !leagueHasClubs(slug)) continue;
    seen.add(slug);
    opts.push({ slug, short: getCompetition(slug)?.short ?? slug });
  }
  return opts.length > 0 ? opts : DRAFT_LEAGUES;
}
