export interface Cromo {
  id: number;
  number: number;
  name: string;
  path: string;
  category: "partidos" | "edicion-especial" | "grupos" | "sedes";
  rarity: "Legendario" | "Oro" | "Plata";
}

export const CROMOS: Cromo[] = [
  { id: 1, number: 1, name: "Cromo #001", path: "/cromos/fase-grupos/partidos/cromo_001_legendario.png", category: "partidos", rarity: "Legendario" },
  { id: 2, number: 2, name: "Cromo #002", path: "/cromos/fase-grupos/partidos/cromo_002_plata.png", category: "partidos", rarity: "Plata" },
  { id: 3, number: 3, name: "Cromo #003", path: "/cromos/fase-grupos/partidos/cromo_003_plata.png", category: "partidos", rarity: "Plata" },
  { id: 4, number: 4, name: "Cromo #004", path: "/cromos/fase-grupos/partidos/cromo_004_oro.png", category: "partidos", rarity: "Oro" },
  { id: 5, number: 5, name: "Cromo #005", path: "/cromos/fase-grupos/partidos/cromo_005_plata.png", category: "partidos", rarity: "Plata" },
  { id: 6, number: 6, name: "Cromo #006", path: "/cromos/fase-grupos/partidos/cromo_006_plata.png", category: "partidos", rarity: "Plata" },
  { id: 7, number: 7, name: "Cromo #007", path: "/cromos/fase-grupos/partidos/cromo_007_legendario.png", category: "partidos", rarity: "Legendario" },
  { id: 8, number: 8, name: "Cromo #008", path: "/cromos/fase-grupos/partidos/cromo_008_plata.png", category: "partidos", rarity: "Plata" },
  { id: 9, number: 9, name: "Cromo #009", path: "/cromos/fase-grupos/partidos/cromo_009_plata.png", category: "partidos", rarity: "Plata" },
  { id: 10, number: 10, name: "Cromo #010", path: "/cromos/fase-grupos/partidos/cromo_010_plata.png", category: "partidos", rarity: "Plata" },
  { id: 11, number: 11, name: "Cromo #011", path: "/cromos/fase-grupos/partidos/cromo_011_oro.png", category: "partidos", rarity: "Oro" },
  { id: 12, number: 12, name: "Cromo #012", path: "/cromos/fase-grupos/partidos/cromo_012_plata.png", category: "partidos", rarity: "Plata" },
  { id: 13, number: 13, name: "Cromo #013", path: "/cromos/fase-grupos/partidos/cromo_013_plata.png", category: "partidos", rarity: "Plata" },
  { id: 14, number: 14, name: "Cromo #014", path: "/cromos/fase-grupos/partidos/cromo_014_plata.png", category: "partidos", rarity: "Plata" },
  { id: 15, number: 15, name: "Cromo #015", path: "/cromos/fase-grupos/partidos/cromo_015_plata.png", category: "partidos", rarity: "Plata" },
  { id: 16, number: 16, name: "Cromo #016", path: "/cromos/fase-grupos/partidos/cromo_016_plata.png", category: "partidos", rarity: "Plata" },
  { id: 17, number: 17, name: "Cromo #017", path: "/cromos/fase-grupos/partidos/cromo_017_legendario.png", category: "partidos", rarity: "Legendario" },
  { id: 18, number: 18, name: "Cromo #018", path: "/cromos/fase-grupos/partidos/cromo_018_plata.png", category: "partidos", rarity: "Plata" },
  { id: 19, number: 19, name: "Cromo #019", path: "/cromos/fase-grupos/partidos/cromo_019_oro.png", category: "partidos", rarity: "Oro" },
  { id: 20, number: 20, name: "Cromo #020", path: "/cromos/fase-grupos/partidos/cromo_020_plata.png", category: "partidos", rarity: "Plata" },
  { id: 21, number: 21, name: "Cromo #021", path: "/cromos/fase-grupos/partidos/cromo_021_legendario.png", category: "partidos", rarity: "Legendario" },
  { id: 22, number: 22, name: "Cromo #022", path: "/cromos/fase-grupos/partidos/cromo_022_plata.png", category: "partidos", rarity: "Plata" },
  { id: 23, number: 23, name: "Cromo #023", path: "/cromos/fase-grupos/partidos/cromo_023_plata.png", category: "partidos", rarity: "Plata" },
  { id: 24, number: 24, name: "Cromo #024", path: "/cromos/fase-grupos/partidos/cromo_024_plata.png", category: "partidos", rarity: "Plata" },
  { id: 25, number: 25, name: "Cromo #025", path: "/cromos/fase-grupos/partidos/cromo_025_plata.png", category: "partidos", rarity: "Plata" },
  { id: 26, number: 26, name: "Cromo #026", path: "/cromos/fase-grupos/partidos/cromo_026_plata.png", category: "partidos", rarity: "Plata" },
  { id: 27, number: 27, name: "Cromo #027", path: "/cromos/fase-grupos/partidos/cromo_027_plata.png", category: "partidos", rarity: "Plata" },
  { id: 28, number: 28, name: "Cromo #028", path: "/cromos/fase-grupos/partidos/cromo_028_oro.png", category: "partidos", rarity: "Oro" },
  { id: 29, number: 29, name: "Cromo #029", path: "/cromos/fase-grupos/partidos/cromo_029_plata.png", category: "partidos", rarity: "Plata" },
  { id: 30, number: 30, name: "Cromo #030", path: "/cromos/fase-grupos/partidos/cromo_030_plata.png", category: "partidos", rarity: "Plata" },
  { id: 31, number: 31, name: "Cromo #031", path: "/cromos/fase-grupos/partidos/cromo_031_plata.png", category: "partidos", rarity: "Plata" },
  { id: 32, number: 32, name: "Cromo #032", path: "/cromos/fase-grupos/partidos/cromo_032_oro.png", category: "partidos", rarity: "Oro" },
  { id: 33, number: 33, name: "Cromo #033", path: "/cromos/fase-grupos/partidos/cromo_033_plata.png", category: "partidos", rarity: "Plata" },
  { id: 34, number: 34, name: "Cromo #034", path: "/cromos/fase-grupos/partidos/cromo_034_plata.png", category: "partidos", rarity: "Plata" },
  { id: 35, number: 35, name: "Cromo #035", path: "/cromos/fase-grupos/partidos/cromo_035_plata.png", category: "partidos", rarity: "Plata" },
  { id: 36, number: 36, name: "Cromo #036", path: "/cromos/fase-grupos/partidos/cromo_036_plata.png", category: "partidos", rarity: "Plata" },
  { id: 37, number: 37, name: "Cromo #037", path: "/cromos/fase-grupos/partidos/cromo_037_plata.png", category: "partidos", rarity: "Plata" },
  { id: 38, number: 38, name: "Cromo #038", path: "/cromos/fase-grupos/partidos/cromo_038_plata.png", category: "partidos", rarity: "Plata" },
  { id: 39, number: 39, name: "Cromo #039", path: "/cromos/fase-grupos/partidos/cromo_039_plata.png", category: "partidos", rarity: "Plata" },
  { id: 40, number: 40, name: "Cromo #040", path: "/cromos/fase-grupos/partidos/cromo_040_plata.png", category: "partidos", rarity: "Plata" },
  { id: 41, number: 41, name: "Cromo #041", path: "/cromos/fase-grupos/partidos/cromo_041_plata.png", category: "partidos", rarity: "Plata" },
  { id: 42, number: 42, name: "Cromo #042", path: "/cromos/fase-grupos/partidos/cromo_042_plata.png", category: "partidos", rarity: "Plata" },
  { id: 43, number: 43, name: "Cromo #043", path: "/cromos/fase-grupos/partidos/cromo_043_plata.png", category: "partidos", rarity: "Plata" },
  { id: 44, number: 44, name: "Cromo #044", path: "/cromos/fase-grupos/partidos/cromo_044_plata.png", category: "partidos", rarity: "Plata" },
  { id: 45, number: 45, name: "Cromo #045", path: "/cromos/fase-grupos/partidos/cromo_045_plata.png", category: "partidos", rarity: "Plata" },
  { id: 46, number: 46, name: "Cromo #046", path: "/cromos/fase-grupos/partidos/cromo_046_plata.png", category: "partidos", rarity: "Plata" },
  { id: 47, number: 47, name: "Cromo #047", path: "/cromos/fase-grupos/partidos/cromo_047_plata.png", category: "partidos", rarity: "Plata" },
  { id: 48, number: 48, name: "Cromo #048", path: "/cromos/fase-grupos/partidos/cromo_048_plata.png", category: "partidos", rarity: "Plata" },
  { id: 49, number: 49, name: "Cromo #049", path: "/cromos/fase-grupos/partidos/cromo_049_oro.png", category: "partidos", rarity: "Oro" },
  { id: 50, number: 50, name: "Cromo #050", path: "/cromos/fase-grupos/partidos/cromo_050_plata.png", category: "partidos", rarity: "Plata" },
  { id: 51, number: 51, name: "Cromo #051", path: "/cromos/fase-grupos/partidos/cromo_051_oro.png", category: "partidos", rarity: "Oro" },
  { id: 52, number: 52, name: "Cromo #052", path: "/cromos/fase-grupos/partidos/cromo_052_plata.png", category: "partidos", rarity: "Plata" },
  { id: 53, number: 53, name: "Cromo #053", path: "/cromos/fase-grupos/partidos/cromo_053_plata.png", category: "partidos", rarity: "Plata" },
  { id: 54, number: 54, name: "Cromo #054", path: "/cromos/fase-grupos/partidos/cromo_054_plata.png", category: "partidos", rarity: "Plata" },
  { id: 55, number: 55, name: "Cromo #055", path: "/cromos/fase-grupos/partidos/cromo_055_plata.png", category: "partidos", rarity: "Plata" },
  { id: 56, number: 56, name: "Cromo #056", path: "/cromos/fase-grupos/partidos/cromo_056_oro.png", category: "partidos", rarity: "Oro" },
  { id: 57, number: 57, name: "Cromo #057", path: "/cromos/fase-grupos/partidos/cromo_057_plata.png", category: "partidos", rarity: "Plata" },
  { id: 58, number: 58, name: "Cromo #058", path: "/cromos/fase-grupos/partidos/cromo_058_plata.png", category: "partidos", rarity: "Plata" },
  { id: 59, number: 59, name: "Cromo #059", path: "/cromos/fase-grupos/partidos/cromo_059_oro.png", category: "partidos", rarity: "Oro" },
  { id: 60, number: 60, name: "Cromo #060", path: "/cromos/fase-grupos/partidos/cromo_060_plata.png", category: "partidos", rarity: "Plata" },
  { id: 61, number: 61, name: "Cromo #061", path: "/cromos/fase-grupos/partidos/cromo_061_plata.png", category: "partidos", rarity: "Plata" },
  { id: 62, number: 62, name: "Cromo #062", path: "/cromos/fase-grupos/partidos/cromo_062_plata.png", category: "partidos", rarity: "Plata" },
  { id: 63, number: 63, name: "Cromo #063", path: "/cromos/fase-grupos/partidos/cromo_063_plata.png", category: "partidos", rarity: "Plata" },
  { id: 64, number: 64, name: "Cromo #064", path: "/cromos/fase-grupos/partidos/cromo_064_plata.png", category: "partidos", rarity: "Plata" },
  { id: 65, number: 65, name: "Cromo #065", path: "/cromos/fase-grupos/partidos/cromo_065_plata.png", category: "partidos", rarity: "Plata" },
  { id: 66, number: 66, name: "Cromo #066", path: "/cromos/fase-grupos/partidos/cromo_066_oro.png", category: "partidos", rarity: "Oro" },
  { id: 67, number: 67, name: "Cromo #067", path: "/cromos/fase-grupos/partidos/cromo_067_plata.png", category: "partidos", rarity: "Plata" },
  { id: 68, number: 68, name: "Cromo #068", path: "/cromos/fase-grupos/partidos/cromo_068_plata.png", category: "partidos", rarity: "Plata" },
  { id: 69, number: 69, name: "Cromo #069", path: "/cromos/fase-grupos/partidos/cromo_069_plata.png", category: "partidos", rarity: "Plata" },
  { id: 70, number: 70, name: "Cromo #070", path: "/cromos/fase-grupos/partidos/cromo_070_plata.png", category: "partidos", rarity: "Plata" },
  { id: 71, number: 71, name: "Cromo #071", path: "/cromos/fase-grupos/partidos/cromo_071_oro.png", category: "partidos", rarity: "Oro" },
  { id: 72, number: 72, name: "Cromo #072", path: "/cromos/fase-grupos/partidos/cromo_072_plata.png", category: "partidos", rarity: "Plata" },
  { id: 73, number: 73, name: "Cromo #073", path: "/cromos/fase-grupos/edicion-especial/cromo_073_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 74, number: 74, name: "Cromo #074", path: "/cromos/fase-grupos/edicion-especial/cromo_074_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 75, number: 75, name: "Cromo #075", path: "/cromos/fase-grupos/edicion-especial/cromo_075_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 76, number: 76, name: "Cromo #076", path: "/cromos/fase-grupos/edicion-especial/cromo_076_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 77, number: 77, name: "Cromo #077", path: "/cromos/fase-grupos/edicion-especial/cromo_077_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 78, number: 78, name: "Cromo #078", path: "/cromos/fase-grupos/edicion-especial/cromo_078_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 79, number: 79, name: "Cromo #079", path: "/cromos/fase-grupos/edicion-especial/cromo_079_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 80, number: 80, name: "Cromo #080", path: "/cromos/fase-grupos/edicion-especial/cromo_080_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 81, number: 81, name: "Cromo #081", path: "/cromos/fase-grupos/edicion-especial/cromo_081_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 82, number: 82, name: "Cromo #082", path: "/cromos/fase-grupos/edicion-especial/cromo_082_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 83, number: 83, name: "Cromo #083", path: "/cromos/fase-grupos/edicion-especial/cromo_083_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 84, number: 84, name: "Cromo #084", path: "/cromos/fase-grupos/edicion-especial/cromo_084_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 85, number: 85, name: "Cromo #085", path: "/cromos/fase-grupos/edicion-especial/cromo_085_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 86, number: 86, name: "Cromo #086", path: "/cromos/fase-grupos/edicion-especial/cromo_086_legendario.png", category: "edicion-especial", rarity: "Legendario" },
  { id: 87, number: 87, name: "Cromo #087", path: "/cromos/fase-grupos/edicion-especial/cromo_087_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 88, number: 88, name: "Cromo #088", path: "/cromos/fase-grupos/edicion-especial/cromo_088_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 89, number: 89, name: "Cromo #089", path: "/cromos/fase-grupos/edicion-especial/cromo_089_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 90, number: 90, name: "Cromo #090", path: "/cromos/fase-grupos/edicion-especial/cromo_090_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 91, number: 91, name: "Cromo #091", path: "/cromos/fase-grupos/edicion-especial/cromo_091_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 92, number: 92, name: "Cromo #092", path: "/cromos/fase-grupos/edicion-especial/cromo_092_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 93, number: 93, name: "Cromo #093", path: "/cromos/fase-grupos/edicion-especial/cromo_093_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 94, number: 94, name: "Cromo #094", path: "/cromos/fase-grupos/edicion-especial/cromo_094_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 95, number: 95, name: "Cromo #095", path: "/cromos/fase-grupos/edicion-especial/cromo_095_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 96, number: 96, name: "Cromo #096", path: "/cromos/fase-grupos/edicion-especial/cromo_096_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 97, number: 97, name: "Cromo #097", path: "/cromos/fase-grupos/edicion-especial/cromo_097_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 98, number: 98, name: "Cromo #098", path: "/cromos/fase-grupos/edicion-especial/cromo_098_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 99, number: 99, name: "Cromo #099", path: "/cromos/fase-grupos/edicion-especial/cromo_099_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 100, number: 100, name: "Cromo #100", path: "/cromos/fase-grupos/edicion-especial/cromo_100_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 101, number: 101, name: "Cromo #101", path: "/cromos/fase-grupos/edicion-especial/cromo_101_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 102, number: 102, name: "Cromo #102", path: "/cromos/fase-grupos/edicion-especial/cromo_102_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 103, number: 103, name: "Cromo #103", path: "/cromos/fase-grupos/edicion-especial/cromo_103_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 104, number: 104, name: "Cromo #104", path: "/cromos/fase-grupos/edicion-especial/cromo_104_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 105, number: 105, name: "Cromo #105", path: "/cromos/fase-grupos/edicion-especial/cromo_105_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 106, number: 106, name: "Cromo #106", path: "/cromos/fase-grupos/edicion-especial/cromo_106_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 107, number: 107, name: "Cromo #107", path: "/cromos/fase-grupos/edicion-especial/cromo_107_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 108, number: 108, name: "Cromo #108", path: "/cromos/fase-grupos/edicion-especial/cromo_108_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 109, number: 109, name: "Cromo #109", path: "/cromos/fase-grupos/edicion-especial/cromo_109_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 110, number: 110, name: "Cromo #110", path: "/cromos/fase-grupos/edicion-especial/cromo_110_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 111, number: 111, name: "Cromo #111", path: "/cromos/fase-grupos/edicion-especial/cromo_111_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 112, number: 112, name: "Cromo #112", path: "/cromos/fase-grupos/edicion-especial/cromo_112_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 113, number: 113, name: "Cromo #113", path: "/cromos/fase-grupos/edicion-especial/cromo_113_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 114, number: 114, name: "Cromo #114", path: "/cromos/fase-grupos/edicion-especial/cromo_114_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 115, number: 115, name: "Cromo #115", path: "/cromos/fase-grupos/edicion-especial/cromo_115_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 116, number: 116, name: "Cromo #116", path: "/cromos/fase-grupos/edicion-especial/cromo_116_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 117, number: 117, name: "Cromo #117", path: "/cromos/fase-grupos/edicion-especial/cromo_117_oro.png", category: "edicion-especial", rarity: "Oro" },
  { id: 118, number: 118, name: "Cromo #118", path: "/cromos/fase-grupos/edicion-especial/cromo_118_plata.png", category: "edicion-especial", rarity: "Plata" },
  { id: 119, number: 119, name: "Cromo #119", path: "/cromos/fase-grupos/edicion-especial/cromo_119_plata.png", category: "edicion-especial", rarity: "Plata" },
  { id: 120, number: 120, name: "Cromo #120", path: "/cromos/fase-grupos/edicion-especial/cromo_120_plata.png", category: "edicion-especial", rarity: "Plata" },
  { id: 121, number: 121, name: "Cromo #121", path: "/cromos/fase-grupos/edicion-especial/cromo_121_plata.png", category: "edicion-especial", rarity: "Plata" },
  { id: 122, number: 122, name: "Cromo #122", path: "/cromos/fase-grupos/edicion-especial/cromo_122_plata.png", category: "edicion-especial", rarity: "Plata" },
  { id: 123, number: 123, name: "Cromo #123", path: "/cromos/fase-grupos/grupos/cromo_123_plata.png", category: "grupos", rarity: "Plata" },
  { id: 124, number: 124, name: "Cromo #124", path: "/cromos/fase-grupos/grupos/cromo_124_plata.png", category: "grupos", rarity: "Plata" },
  { id: 125, number: 125, name: "Cromo #125", path: "/cromos/fase-grupos/grupos/cromo_125_plata.png", category: "grupos", rarity: "Plata" },
  { id: 126, number: 126, name: "Cromo #126", path: "/cromos/fase-grupos/grupos/cromo_126_plata.png", category: "grupos", rarity: "Plata" },
  { id: 127, number: 127, name: "Cromo #127", path: "/cromos/fase-grupos/grupos/cromo_127_plata.png", category: "grupos", rarity: "Plata" },
  { id: 128, number: 128, name: "Cromo #128", path: "/cromos/fase-grupos/grupos/cromo_128_plata.png", category: "grupos", rarity: "Plata" },
  { id: 129, number: 129, name: "Cromo #129", path: "/cromos/fase-grupos/grupos/cromo_129_plata.png", category: "grupos", rarity: "Plata" },
  { id: 130, number: 130, name: "Cromo #130", path: "/cromos/fase-grupos/grupos/cromo_130_plata.png", category: "grupos", rarity: "Plata" },
  { id: 131, number: 131, name: "Cromo #131", path: "/cromos/fase-grupos/grupos/cromo_131_plata.png", category: "grupos", rarity: "Plata" },
  { id: 132, number: 132, name: "Cromo #132", path: "/cromos/fase-grupos/grupos/cromo_132_plata.png", category: "grupos", rarity: "Plata" },
  { id: 133, number: 133, name: "Cromo #133", path: "/cromos/fase-grupos/grupos/cromo_133_plata.png", category: "grupos", rarity: "Plata" },
  { id: 134, number: 134, name: "Cromo #134", path: "/cromos/fase-grupos/grupos/cromo_134_plata.png", category: "grupos", rarity: "Plata" },
  { id: 135, number: 135, name: "Cromo #135", path: "/cromos/fase-grupos/sedes/cromo_135_plata.png", category: "sedes", rarity: "Plata" },
  { id: 136, number: 136, name: "Cromo #136", path: "/cromos/fase-grupos/sedes/cromo_136_plata.png", category: "sedes", rarity: "Plata" },
  { id: 137, number: 137, name: "Cromo #137", path: "/cromos/fase-grupos/sedes/cromo_137_plata.png", category: "sedes", rarity: "Plata" },
  { id: 138, number: 138, name: "Cromo #138", path: "/cromos/fase-grupos/sedes/cromo_138_plata.png", category: "sedes", rarity: "Plata" },
  { id: 139, number: 139, name: "Cromo #139", path: "/cromos/fase-grupos/sedes/cromo_139_plata.png", category: "sedes", rarity: "Plata" },
  { id: 140, number: 140, name: "Cromo #140", path: "/cromos/fase-grupos/sedes/cromo_140_plata.png", category: "sedes", rarity: "Plata" },
  { id: 141, number: 141, name: "Cromo #141", path: "/cromos/fase-grupos/sedes/cromo_141_plata.png", category: "sedes", rarity: "Plata" },
  { id: 142, number: 142, name: "Cromo #142", path: "/cromos/fase-grupos/sedes/cromo_142_plata.png", category: "sedes", rarity: "Plata" },
  { id: 143, number: 143, name: "Cromo #143", path: "/cromos/fase-grupos/sedes/cromo_143_plata.png", category: "sedes", rarity: "Plata" },
  { id: 144, number: 144, name: "Cromo #144", path: "/cromos/fase-grupos/sedes/cromo_144_plata.png", category: "sedes", rarity: "Plata" },
  { id: 145, number: 145, name: "Cromo #145", path: "/cromos/fase-grupos/sedes/cromo_145_plata.png", category: "sedes", rarity: "Plata" },
  { id: 146, number: 146, name: "Cromo #146", path: "/cromos/fase-grupos/sedes/cromo_146_plata.png", category: "sedes", rarity: "Plata" },
  { id: 147, number: 147, name: "Cromo #147", path: "/cromos/fase-grupos/sedes/cromo_147_plata.png", category: "sedes", rarity: "Plata" },
  { id: 148, number: 148, name: "Cromo #148", path: "/cromos/fase-grupos/sedes/cromo_148_plata.png", category: "sedes", rarity: "Plata" },
  { id: 149, number: 149, name: "Cromo #149", path: "/cromos/fase-grupos/sedes/cromo_149_plata.png", category: "sedes", rarity: "Plata" },
  { id: 150, number: 150, name: "Cromo #150", path: "/cromos/fase-grupos/sedes/cromo_150_plata.png", category: "sedes", rarity: "Plata" },
];

export const CATEGORIES = [
  { key: "partidos", label: { es: "Partidos", en: "Matches" }, count: 72 },
  { key: "edicion-especial", label: { es: "Edición Especial", en: "Special Edition" }, count: 50 },
  { key: "grupos", label: { es: "Grupos", en: "Groups" }, count: 12 },
  { key: "sedes", label: { es: "Sedes", en: "Venues" }, count: 16 },
] as const;

// Los conteos se derivan de CROMOS para que nunca se desincronicen del catálogo
// real: antes estaban hardcodeados a 14/36/100 y no cuadraban con los 18/42/90
// reales, mostrando cifras contradictorias en /cromos y en el álbum.
export const RARITIES = [
  { key: "Legendario", label: { es: "Legendario", en: "Legendary" }, count: CROMOS.filter((c) => c.rarity === "Legendario").length, color: "#f59e0b", glow: "rgba(245,158,11,0.4)" },
  { key: "Oro", label: { es: "Oro", en: "Gold" }, count: CROMOS.filter((c) => c.rarity === "Oro").length, color: "#eab308", glow: "rgba(234,179,8,0.35)" },
  { key: "Plata", label: { es: "Plata", en: "Silver" }, count: CROMOS.filter((c) => c.rarity === "Plata").length, color: "#a69a82", glow: "rgba(148,163,184,0.3)" },
] as const;

export const TOTAL_CROMOS = 150;